export interface JuniorDriver {
  id: string;
  name: string;
  code: string;
  number: number;
  country: string;
  countryFlag: string;
  team: string;
  f1Academy?: string;
  f1AcademyColor?: string;
  points: number;
  position: number;
  wins: number;
  podiums: number;
  poles: number;
  headshotUrl?: string;
  bio?: string;
}

export interface JuniorTeam {
  name: string;
  points: number;
  position: number;
  color: string;
  base?: string;
}

export interface JuniorRaceWeekend {
  round: number;
  gpName: string;
  circuit: string;
  countryFlag: string;
  date: string;
  isCompleted: boolean;
  sprintWinner?: string;
  featureWinner?: string;
  polePosition?: string;
  fastestLap?: string;
}

export interface JuniorCarSpecs {
  model: string;
  chassis: string;
  engine: string;
  power: string;
  topSpeed: string;
  acceleration: string;
  gearbox: string;
  weight: string;
  tyres: string;
  fuel: string;
}

export interface JuniorSeriesData {
  seriesId: 'f2' | 'f3' | 'academy';
  seriesName: string;
  championshipYear: string;
  description: string;
  regulations: string;
  carSpecs: JuniorCarSpecs;
  drivers: JuniorDriver[];
  teams: JuniorTeam[];
  calendar: JuniorRaceWeekend[];
}

export const JUNIOR_SERIES_DATABASE: Record<'f2' | 'f3' | 'academy', JuniorSeriesData> = {
  f2: {
    seriesId: 'f2',
    seriesName: 'FIA Formula 2 Championship',
    championshipYear: '2026',
    description: 'Premier single-spec feeder championship directly below Formula 1. Powered by Mecachrome 3.4L V6 Turbo engines with 100% Aramco sustainable fuel.',
    regulations: 'Sprint Race (Reverse top 10, 10-1 pts) & Feature Race (Mandatory pit stop, 25-1 pts). 2 pts for Pole Position, 1 pt for Fastest Lap.',
    carSpecs: {
      model: 'Dallara F2 2024 Chassis',
      chassis: 'Carbon-fibre monocoque with FIA Halo 3D safety structure & ground-effect floor',
      engine: 'Mecachrome 3.4L Single Turbocharged V6 Engine',
      power: '620 HP @ 8,750 RPM (Maximum Torque: 570 Nm @ 6,000 RPM)',
      topSpeed: '335 km/h (208 mph) with DRS open at Monza / Baku',
      acceleration: '0–100 km/h in 2.85 seconds; 0–200 km/h in 6.60 seconds',
      gearbox: 'Hewland 6-speed longitudinal paddle-shift electro-hydraulic sequential',
      weight: '795 kg (minimum weight including driver and ballast)',
      tyres: 'Pirelli P Zero 18-inch slick compounds (Hard, Medium, Soft, SuperSoft & Wet)',
      fuel: '100% Aramco Advanced Synthetic Sustainable Fuel',
    },
    drivers: [
      {
        id: 'camara',
        name: 'Rafael Câmara',
        code: 'CAM',
        number: 1,
        country: 'Brazil',
        countryFlag: '🇧🇷',
        team: 'Invicta Racing',
        f1Academy: 'Ferrari Driver Academy',
        f1AcademyColor: '#E8002D',
        points: 168,
        position: 1,
        wins: 4,
        podiums: 8,
        poles: 3,
        headshotUrl: 'https://res.cloudinary.com/prod-f2f3/c_lfill,w_300/q_auto/v1770000000/common/f2/2026/invictaracing/rafcam01/2026invictaracingrafcam01right.webp',
        bio: 'FRECA Champion & Ferrari Driver Academy star making an impressive F2 campaign with Invicta Racing.',
      },
      {
        id: 'durksen',
        name: 'Joshua Dürksen',
        code: 'DUR',
        number: 2,
        country: 'Paraguay',
        countryFlag: '🇵🇾',
        team: 'Invicta Racing',
        f1Academy: 'Independent Sensation',
        f1AcademyColor: '#3671C6',
        points: 154,
        position: 2,
        wins: 3,
        podiums: 7,
        poles: 2,
        headshotUrl: 'https://res.cloudinary.com/prod-f2f3/c_lfill,w_300/q_auto/v1770000000/common/f2/2026/invictaracing/josdur01/2026invictaracingjosdur01right.webp',
        bio: 'Paraguayan trailblazer who captured historic F2 Feature Race victory at Baku.',
      },
      {
        id: 'miyata',
        name: 'Ritomo Miyata',
        code: 'MIY',
        number: 3,
        country: 'Japan',
        countryFlag: '🇯🇵',
        team: 'Hitech Pulse-Eight',
        f1Academy: 'Toyota Gazoo Racing',
        f1AcademyColor: '#E8002D',
        points: 142,
        position: 3,
        wins: 3,
        podiums: 6,
        poles: 2,
        headshotUrl: 'https://res.cloudinary.com/prod-f2f3/c_lfill,w_300/q_auto/v1770000000/common/f2/2026/hitech/ritmiy01/2026hitechritmiy01right.webp',
        bio: 'Super Formula and Super GT Champion who made an explosive transition to European racing with Hitech.',
      },
      {
        id: 'herta',
        name: 'Colton Herta',
        code: 'HER',
        number: 4,
        country: 'United States',
        countryFlag: '🇺🇸',
        team: 'Hitech Pulse-Eight',
        f1Academy: 'Cadillac F1 Target',
        f1AcademyColor: '#FFC72C',
        points: 136,
        position: 4,
        wins: 2,
        podiums: 6,
        poles: 3,
        headshotUrl: 'https://res.cloudinary.com/prod-f2f3/c_lfill,w_300/q_auto/v1770000000/common/f2/2026/hitech/colher01/2026hitechcolher01right.webp',
        bio: 'IndyCar superstar and youngest winner in IndyCar history, competing in FIA F2 to earn F1 Super Licence points.',
      },
      {
        id: 'leon',
        name: 'Noel León',
        code: 'LEO',
        number: 5,
        country: 'Mexico',
        countryFlag: '🇲🇽',
        team: 'Campos Racing',
        f1Academy: 'Red Bull Junior Team',
        f1AcademyColor: '#3671C6',
        points: 124,
        position: 5,
        wins: 2,
        podiums: 5,
        poles: 1,
        headshotUrl: 'https://res.cloudinary.com/prod-f2f3/c_lfill,w_300/q_auto/v1770000000/common/f2/2026/camposracing/noeleo01/2026camposracingnoeleo01right.webp',
        bio: 'Euroformula Champion and Red Bull Junior driver impressing with Campos Racing.',
      },
      {
        id: 'tsolov',
        name: 'Nikola Tsolov',
        code: 'TSO',
        number: 6,
        country: 'Bulgaria',
        countryFlag: '🇧🇬',
        team: 'Campos Racing',
        f1Academy: 'Red Bull Junior Team',
        f1AcademyColor: '#3671C6',
        points: 118,
        position: 6,
        wins: 2,
        podiums: 4,
        poles: 1,
        headshotUrl: 'https://res.cloudinary.com/prod-f2f3/c_lfill,w_300/q_auto/v1770000000/common/f2/2026/camposracing/niktso01/2026camposracingniktso01right.webp',
        bio: 'The Bulgarian Lion known for fearless overtaking maneuvers.',
      },
      {
        id: 'beganovic',
        name: 'Dino Beganovic',
        code: 'BEG',
        number: 7,
        country: 'Sweden',
        countryFlag: '🇸🇪',
        team: 'DAMS Lucas Oil',
        f1Academy: 'Ferrari Driver Academy',
        f1AcademyColor: '#E8002D',
        points: 112,
        position: 7,
        wins: 1,
        podiums: 5,
        poles: 2,
        headshotUrl: 'https://res.cloudinary.com/prod-f2f3/c_lfill,w_300/q_auto/v1770000000/common/f2/2026/damslucasoil/dinbeg01/2026damslucasoildinbeg01right.webp',
        bio: 'FRECA Champion and Ferrari Driver Academy protege stepping up to F2 with DAMS.',
      },
      {
        id: 'bilinski',
        name: 'Roman Bilinski',
        code: 'BIL',
        number: 8,
        country: 'Poland',
        countryFlag: '🇵🇱',
        team: 'DAMS Lucas Oil',
        f1Academy: 'FR Oceania Champion',
        f1AcademyColor: '#FF8000',
        points: 98,
        position: 8,
        wins: 1,
        podiums: 4,
        poles: 0,
        headshotUrl: 'https://res.cloudinary.com/prod-f2f3/c_lfill,w_300/q_auto/v1770000000/common/f2/2026/damslucasoil/rombil01/2026damslucasoilrombil01right.webp',
        bio: 'Formula Regional Oceania Champion who established himself as a Feature Race contender.',
      },
      {
        id: 'mini',
        name: 'Gabriele Minì',
        code: 'MIN',
        number: 9,
        country: 'Italy',
        countryFlag: '🇮🇹',
        team: 'MP Motorsport',
        f1Academy: 'Alpine Academy',
        f1AcademyColor: '#0090FF',
        points: 94,
        position: 9,
        wins: 2,
        podiums: 4,
        poles: 1,
        headshotUrl: 'https://res.cloudinary.com/prod-f2f3/c_lfill,w_300/q_auto/v1770000000/common/f2/2026/mpmotorsport/gabmin01/2026mpmotorsportgabmin01right.webp',
        bio: 'Monaco F3 winner and Alpine Academy Italian prodigy stepping up into F2.',
      },
      {
        id: 'goethe',
        name: 'Oliver Goethe',
        code: 'GOE',
        number: 10,
        country: 'Germany',
        countryFlag: '🇩🇪',
        team: 'MP Motorsport',
        f1Academy: 'Red Bull Junior Team',
        f1AcademyColor: '#3671C6',
        points: 88,
        position: 10,
        wins: 1,
        podiums: 4,
        poles: 1,
        headshotUrl: 'https://res.cloudinary.com/prod-f2f3/c_lfill,w_300/q_auto/v1770000000/common/f2/2026/mpmotorsport/oligoe01/2026mpmotorsportoligoe01right.webp',
        bio: 'Red Bull Junior driver with dominant race victories across European circuits.',
      },
      {
        id: 'montoya',
        name: 'Sebastian Montoya',
        code: 'MOY',
        number: 11,
        country: 'Colombia',
        countryFlag: '🇨🇴',
        team: 'PREMA Racing',
        f1Academy: 'Red Bull Junior Team',
        f1AcademyColor: '#3671C6',
        points: 82,
        position: 11,
        wins: 1,
        podiums: 3,
        poles: 0,
        headshotUrl: 'https://res.cloudinary.com/prod-f2f3/c_lfill,w_300/q_auto/v1770000000/common/f2/2026/premaracing/sebmon01/2026premaracingsebmon01right.webp',
        bio: 'Son of F1 icon Juan Pablo Montoya, showcasing aggressive wheel-to-wheel racing for PREMA.',
      },
      {
        id: 'boya',
        name: 'Mari Boya',
        code: 'BOY',
        number: 12,
        country: 'Spain',
        countryFlag: '🇪🇸',
        team: 'PREMA Racing',
        f1Academy: 'Aston Martin Driver Development',
        f1AcademyColor: '#229971',
        points: 76,
        position: 12,
        wins: 1,
        podiums: 3,
        poles: 0,
        headshotUrl: 'https://res.cloudinary.com/prod-f2f3/c_lfill,w_300/q_auto/v1770000000/common/f2/2026/premaracing/marboy01/2026premaracingmarboy01right.webp',
        bio: 'Spanish Feature Race winner with PREMA Racing.',
      },
      {
        id: 'stenshorne',
        name: 'Martinius Stenshorne',
        code: 'STE',
        number: 14,
        country: 'Norway',
        countryFlag: '🇳🇴',
        team: 'Rodin Motorsport',
        f1Academy: 'McLaren Driver Development',
        f1AcademyColor: '#FF8000',
        points: 72,
        position: 13,
        wins: 1,
        podiums: 2,
        poles: 0,
        headshotUrl: 'https://res.cloudinary.com/prod-f2f3/c_lfill,w_300/q_auto/v1770000000/common/f2/2026/rodinmotorsport/marste01/2026rodinmotorsportmarste01right.webp',
        bio: 'FRECA runner-up and McLaren Development Driver racing for Rodin Motorsport.',
      },
      {
        id: 'dunne',
        name: 'Alex Dunne',
        code: 'DUN',
        number: 15,
        country: 'Ireland',
        countryFlag: '🇮🇪',
        team: 'Rodin Motorsport',
        f1Academy: 'McLaren Driver Development',
        f1AcademyColor: '#FF8000',
        points: 68,
        position: 14,
        wins: 0,
        podiums: 3,
        poles: 1,
        headshotUrl: 'https://res.cloudinary.com/prod-f2f3/c_lfill,w_300/q_auto/v1770000000/common/f2/2026/rodinmotorsport/aledun01/2026rodinmotorsportaledun01right.webp',
        bio: 'British F4 Champion and McLaren Young Driver standout.',
      },
      {
        id: 'maini',
        name: 'Kush Maini',
        code: 'MAI',
        number: 16,
        country: 'India',
        countryFlag: '🇮🇳',
        team: 'ART Grand Prix',
        f1Academy: 'Alpine Academy',
        f1AcademyColor: '#0090FF',
        points: 64,
        position: 15,
        wins: 1,
        podiums: 2,
        poles: 1,
        headshotUrl: 'https://res.cloudinary.com/prod-f2f3/c_lfill,w_300/q_auto/v1770000000/common/f2/2026/artgrandprix/kusmai01/2026artgrandprixkusmai01right.webp',
        bio: 'Alpine Academy driver and Formula 2 winner from India delivering high-speed qualifying laps.',
      },
      {
        id: 'inthraphuvasak',
        name: 'Tasanapol Inthraphuvasak',
        code: 'INT',
        number: 17,
        country: 'Thailand',
        countryFlag: '🇹🇭',
        team: 'ART Grand Prix',
        f1Academy: 'Independent Sensation',
        f1AcademyColor: '#3671C6',
        points: 58,
        position: 16,
        wins: 0,
        podiums: 2,
        poles: 0,
        headshotUrl: 'https://res.cloudinary.com/prod-f2f3/c_lfill,w_300/q_auto/v1770000000/common/f2/2026/artgrandprix/tasint01/2026artgrandprixtasint01right.webp',
        bio: 'Thai rising star making his full season debut with ART Grand Prix.',
      },
      {
        id: 'fittipaldi',
        name: 'Emerson Fittipaldi Jr.',
        code: 'FIT',
        number: 18,
        country: 'Brazil',
        countryFlag: '🇧🇷',
        team: 'AIX Racing',
        f1Academy: 'Red Bull Junior Team',
        f1AcademyColor: '#3671C6',
        points: 52,
        position: 17,
        wins: 0,
        podiums: 2,
        poles: 0,
        headshotUrl: 'https://res.cloudinary.com/prod-f2f3/c_lfill,w_300/q_auto/v1770000000/common/f2/2026/aixracing/emefit02/2026aixracingemefit02right.webp',
        bio: 'Son of 2-time F1 World Champion Emerson Fittipaldi, backed by Red Bull.',
      },
      {
        id: 'shields',
        name: 'Cian Shields',
        code: 'SHI',
        number: 19,
        country: 'Great Britain',
        countryFlag: '🇬🇧',
        team: 'AIX Racing',
        f1Academy: 'Independent Sensation',
        f1AcademyColor: '#3671C6',
        points: 44,
        position: 18,
        wins: 0,
        podiums: 1,
        poles: 0,
        headshotUrl: 'https://res.cloudinary.com/prod-f2f3/c_lfill,w_300/q_auto/v1770000000/common/f2/2026/aixracing/ciashi01/2026aixracingciashi01right.webp',
        bio: 'British driver stepping up through European single-seater ranks.',
      },
      {
        id: 'yamakoshi',
        name: 'Hiyu Yamakoshi',
        code: 'YAM',
        number: 20,
        country: 'Japan',
        countryFlag: '🇯🇵',
        team: 'Van Amersfoort Racing',
        f1Academy: 'Honda Junior Driver',
        f1AcademyColor: '#E8002D',
        points: 38,
        position: 19,
        wins: 0,
        podiums: 1,
        poles: 0,
        headshotUrl: 'https://res.cloudinary.com/prod-f2f3/c_lfill,w_300/q_auto/v1770000000/common/f2/2026/vanamersfoortracing/hiyyam01/2026vanamersfoortracinghiyyam01right.webp',
        bio: 'Italian F4 runner-up and Honda Formula Dream Project driver.',
      },
      {
        id: 'villagomez',
        name: 'Rafael Villagómez',
        code: 'VIL',
        number: 21,
        country: 'Mexico',
        countryFlag: '🇲🇽',
        team: 'Van Amersfoort Racing',
        f1Academy: 'Independent Sensation',
        f1AcademyColor: '#3671C6',
        points: 32,
        position: 20,
        wins: 0,
        podiums: 1,
        poles: 0,
        headshotUrl: 'https://res.cloudinary.com/prod-f2f3/c_lfill,w_300/q_auto/v1770000000/common/f2/2026/vanamersfoortracing/rafvil01/2026vanamersfoortracingrafvil01right.webp',
        bio: 'Mexican Formula 2 contender returning with Van Amersfoort Racing.',
      },
      {
        id: 'vanhoepen',
        name: 'Laurens van Hoepen',
        code: 'HOE',
        number: 22,
        country: 'Netherlands',
        countryFlag: '🇳🇱',
        team: 'Trident',
        f1Academy: 'ART Academy',
        f1AcademyColor: '#0090FF',
        points: 28,
        position: 21,
        wins: 0,
        podiums: 1,
        poles: 0,
        headshotUrl: 'https://res.cloudinary.com/prod-f2f3/c_lfill,w_300/q_auto/v1770000000/common/f2/2026/trident/lauvan01/2026tridentlauvan01right.webp',
        bio: 'Dutch podium finisher and FRECA star stepping up to F2 with Trident.',
      },
      {
        id: 'bennett',
        name: 'John Bennett',
        code: 'BEN',
        number: 23,
        country: 'Great Britain',
        countryFlag: '🇬🇧',
        team: 'Trident',
        f1Academy: 'Independent Sensation',
        f1AcademyColor: '#3671C6',
        points: 22,
        position: 22,
        wins: 0,
        podiums: 0,
        poles: 0,
        headshotUrl: 'https://res.cloudinary.com/prod-f2f3/c_lfill,w_300/q_auto/v1770000000/common/f2/2026/trident/johben01/2026tridentjohben01right.webp',
        bio: 'GB3 Championship runner-up joining Trident for Formula 2.',
      },
    ],
    teams: [
      { name: 'Invicta Racing', points: 322, position: 1, color: '#FCD800', base: 'Attleborough, United Kingdom' },
      { name: 'Hitech Pulse-Eight', points: 278, position: 2, color: '#002F6C', base: 'Silverstone, United Kingdom' },
      { name: 'Campos Racing', points: 242, position: 3, color: '#E8002D', base: 'Alzira, Spain' },
      { name: 'DAMS Lucas Oil', points: 210, position: 4, color: '#00A0DE', base: 'Le Mans, France' },
      { name: 'MP Motorsport', points: 182, position: 5, color: '#FF4500', base: 'Westmaas, Netherlands' },
      { name: 'PREMA Racing', points: 158, position: 6, color: '#E8002D', base: 'Grisignano di Zocco, Italy' },
      { name: 'Rodin Motorsport', points: 140, position: 7, color: '#FF8000', base: 'Farnham, United Kingdom' },
      { name: 'ART Grand Prix', points: 122, position: 8, color: '#FFFFFF', base: 'Villeneuve-la-Guyard, France' },
      { name: 'AIX Racing', points: 96, position: 9, color: '#3671C6', base: 'Nurburgring, Germany' },
      { name: 'Van Amersfoort Racing', points: 70, position: 10, color: '#FF8000', base: 'Zeewolde, Netherlands' },
      { name: 'Trident', points: 50, position: 11, color: '#00A0DE', base: 'Milan, Italy' },
    ],
    calendar: [
      { round: 1, gpName: 'Bahrain Grand Prix', circuit: 'Bahrain International Circuit', countryFlag: '🇧🇭', date: '28 FEB – 02 MAR', isCompleted: true, sprintWinner: 'Ritomo Miyata', featureWinner: 'Rafael Câmara', polePosition: 'Rafael Câmara', fastestLap: 'Rafael Câmara' },
      { round: 2, gpName: 'Saudi Arabian Grand Prix', circuit: 'Jeddah Corniche Circuit', countryFlag: '🇸🇦', date: '07 MAR – 09 MAR', isCompleted: true, sprintWinner: 'Kush Maini', featureWinner: 'Dino Beganovic', polePosition: 'Dino Beganovic', fastestLap: 'Kush Maini' },
      { round: 3, gpName: 'Australian Grand Prix', circuit: 'Albert Park Circuit', countryFlag: '🇦🇺', date: '22 MAR – 24 MAR', isCompleted: true, sprintWinner: 'Joshua Dürksen', featureWinner: 'Ritomo Miyata', polePosition: 'Ritomo Miyata', fastestLap: 'Colton Herta' },
      { round: 4, gpName: 'Emilia Romagna Grand Prix', circuit: 'Autodromo Enzo e Dino Ferrari', countryFlag: '🇮🇹', date: '17 MAY – 19 MAY', isCompleted: true, sprintWinner: 'Noel León', featureWinner: 'Oliver Goethe', polePosition: 'Kush Maini', fastestLap: 'Noel León' },
      { round: 5, gpName: 'Monaco Grand Prix', circuit: 'Circuit de Monaco', countryFlag: '🇲🇨', date: '24 MAY – 26 MAY', isCompleted: true, sprintWinner: 'Gabriele Minì', featureWinner: 'Colton Herta', polePosition: 'Colton Herta', fastestLap: 'Colton Herta' },
      { round: 6, gpName: 'Spanish Grand Prix', circuit: 'Circuit de Barcelona-Catalunya', countryFlag: '🇪🇸', date: '21 JUN – 23 JUN', isCompleted: true, sprintWinner: 'Sebastian Montoya', featureWinner: 'Rafael Câmara', polePosition: 'Rafael Câmara', fastestLap: 'Rafael Câmara' },
      { round: 7, gpName: 'Austrian Grand Prix', circuit: 'Red Bull Ring', countryFlag: '🇦🇹', date: '28 JUN – 30 JUN', isCompleted: true, sprintWinner: 'Roman Bilinski', featureWinner: 'Dino Beganovic', polePosition: 'Dino Beganovic', fastestLap: 'Dino Beganovic' },
      { round: 8, gpName: 'British Grand Prix', circuit: 'Silverstone Circuit', countryFlag: '🇬🇧', date: '05 JUL – 07 JUL', isCompleted: true, sprintWinner: 'Oliver Goethe', featureWinner: 'Kush Maini', polePosition: 'Kush Maini', fastestLap: 'Gabriele Minì' },
      { round: 9, gpName: 'Hungarian Grand Prix', circuit: 'Hungaroring', countryFlag: '🇭🇺', date: '19 JUL – 21 JUL', isCompleted: true, sprintWinner: 'Ritomo Miyata', featureWinner: 'Noel León', polePosition: 'Ritomo Miyata', fastestLap: 'Ritomo Miyata' },
      { round: 10, gpName: 'Belgian Grand Prix', circuit: 'Circuit de Spa-Francorchamps', countryFlag: '🇧🇪', date: '26 JUL – 28 JUL', isCompleted: true, sprintWinner: 'Dino Beganovic', featureWinner: 'Colton Herta', polePosition: 'Colton Herta', fastestLap: 'Kush Maini' },
      { round: 11, gpName: 'Dutch Grand Prix', circuit: 'Circuit Zandvoort', countryFlag: '🇳🇱', date: '23 AUG – 25 AUG', isCompleted: true, sprintWinner: 'Kush Maini', featureWinner: 'Ritomo Miyata', polePosition: 'Ritomo Miyata', fastestLap: 'Ritomo Miyata' },
      { round: 12, gpName: 'Italian Grand Prix', circuit: 'Autodromo Nazionale Monza', countryFlag: '🇮🇹', date: '30 AUG – 01 SEP', isCompleted: true, sprintWinner: 'Joshua Dürksen', featureWinner: 'Gabriele Minì', polePosition: 'Gabriele Minì', fastestLap: 'Joshua Dürksen' },
      { round: 13, gpName: 'Azerbaijan Grand Prix', circuit: 'Baku City Circuit', countryFlag: '🇦🇿', date: '13 SEP – 15 SEP', isCompleted: false },
      { round: 14, gpName: 'Abu Dhabi Grand Prix', circuit: 'Yas Marina Circuit', countryFlag: '🇦🇪', date: '06 DEC – 08 DEC', isCompleted: false },
    ],
  },
  f3: {
    seriesId: 'f3',
    seriesName: 'FIA Formula 3 Championship',
    championshipYear: '2026',
    description: 'Ultra-competitive 30-car junior proving ground for future F1 superstars. Equal Mecachrome 3.4L V6 engines with intense wheel-to-wheel Sprint & Feature racing.',
    regulations: 'Sprint Race (Reverse top 12 grid, 10-1 pts) & Feature Race (25-1 pts). 2 pts for Pole Position, 1 pt for Fastest Lap in top 10.',
    carSpecs: {
      model: 'Dallara F3 2025 Next-Gen Chassis',
      chassis: 'Carbon-composite monocoque with FIA 2025 impact structures & anti-wheel-climb nose',
      engine: 'Mecachrome 3.4L Naturally Aspirated V6 Engine',
      power: '380 HP @ 8,000 RPM',
      topSpeed: '300 km/h (186 mph) with DRS open',
      acceleration: '0–100 km/h in 3.0 seconds; 0–200 km/h in 7.7 seconds',
      gearbox: 'Hewland 6-speed longitudinal paddle-shift sequential gearbox',
      weight: '690 kg (minimum weight including driver)',
      tyres: 'Pirelli 13-inch bespoke Formula 3 compounds',
      fuel: '100% Aramco Sustainable Synthetic Racing Fuel',
    },
    drivers: [
      {
        id: 'slater',
        name: 'Freddie Slater',
        code: 'SLA',
        number: 1,
        country: 'United Kingdom',
        countryFlag: '🇬🇧',
        team: 'Trident',
        f1Academy: 'Red Bull Junior Team',
        f1AcademyColor: '#3671C6',
        points: 145,
        position: 1,
        wins: 4,
        podiums: 7,
        poles: 3,
        headshotUrl: 'https://res.cloudinary.com/prod-f2f3/c_lfill,w_300/q_auto/v1770000000/common/f3/2026/trident/fresla01/2026tridentfresla01right.webp',
        bio: 'Italian F4 champion and karting legend who took the F3 championship by storm with Trident.',
      },
      {
        id: 'taponen',
        name: 'Tuukka Taponen',
        code: 'TAP',
        number: 2,
        country: 'Finland',
        countryFlag: '🇫🇮',
        team: 'MP Motorsport',
        f1Academy: 'Ferrari Driver Academy',
        f1AcademyColor: '#E8002D',
        points: 109,
        position: 2,
        wins: 3,
        podiums: 5,
        poles: 2,
        headshotUrl: 'https://res.cloudinary.com/prod-f2f3/c_lfill,w_300/q_auto/v1770000000/common/f3/2026/mpmotorsport/tuutap01/2026mpmotorsporttuutap01right.webp',
        bio: 'Finnish flying sensation and Ferrari protege with wins at Spa and Red Bull Ring.',
      },
      {
        id: 'ugochukwu',
        name: 'Ugo Ugochukwu',
        code: 'UGO',
        number: 3,
        country: 'United States',
        countryFlag: '🇺🇸',
        team: 'Campos Racing',
        f1Academy: 'McLaren Driver Development',
        f1AcademyColor: '#FF8000',
        points: 102,
        position: 3,
        wins: 2,
        podiums: 5,
        poles: 1,
        headshotUrl: 'https://res.cloudinary.com/prod-f2f3/c_lfill,w_300/q_auto/v1770000000/common/f3/2026/camposracing/ugougo01/2026camposracingugougo01right.webp',
        bio: 'Macau Grand Prix winner and McLaren Young Driver prodigy.',
      },
      {
        id: 'naael',
        name: 'Théophile Naael',
        code: 'NAA',
        number: 4,
        country: 'France',
        countryFlag: '🇫🇷',
        team: 'Campos Racing',
        f1Academy: 'Alpine Academy',
        f1AcademyColor: '#0090FF',
        points: 94,
        position: 4,
        wins: 2,
        podiums: 4,
        poles: 1,
        headshotUrl: 'https://res.cloudinary.com/prod-f2f3/c_lfill,w_300/q_auto/v1770000000/common/f3/2026/camposracing/thenae01/2026camposracingthenae01right.webp',
        bio: 'Spanish F4 Champion and Alpine Academy star racing for Campos Racing.',
      },
      {
        id: 'strømsted',
        name: 'Noah Strømsted',
        code: 'STR',
        number: 5,
        country: 'Denmark',
        countryFlag: '🇩🇰',
        team: 'Trident',
        f1Academy: 'Independent Sensation',
        f1AcademyColor: '#3671C6',
        points: 88,
        position: 5,
        wins: 1,
        podiums: 4,
        poles: 1,
        headshotUrl: 'https://res.cloudinary.com/prod-f2f3/c_lfill,w_300/q_auto/v1770000000/common/f3/2026/trident/noastr01/2026tridentnoastr01right.webp',
        bio: 'Danish Formula 3 contender delivering consistent podium finishes.',
      },
      {
        id: 'dePalo',
        name: 'Matteo De Palo',
        code: 'DEP',
        number: 6,
        country: 'Italy',
        countryFlag: '🇮🇹',
        team: 'Trident',
        f1Academy: 'Independent Sensation',
        f1AcademyColor: '#3671C6',
        points: 82,
        position: 6,
        wins: 1,
        podiums: 3,
        poles: 1,
        headshotUrl: 'https://res.cloudinary.com/prod-f2f3/c_lfill,w_300/q_auto/v1770000000/common/f3/2026/trident/matdep01/2026tridentmatdep01right.webp',
        bio: 'Italian driver impressing with speed and consistency at Trident.',
      },
    ],
    teams: [
      { name: 'Trident', points: 315, position: 1, color: '#00A0DE', base: 'Milan, Italy' },
      { name: 'Campos Racing', points: 284, position: 2, color: '#E8002D', base: 'Alzira, Spain' },
      { name: 'MP Motorsport', points: 242, position: 3, color: '#FF4500', base: 'Westmaas, Netherlands' },
      { name: 'PREMA Racing', points: 198, position: 4, color: '#E8002D', base: 'Grisignano di Zocco, Italy' },
      { name: 'ART Grand Prix', points: 165, position: 5, color: '#FFFFFF', base: 'Villeneuve-la-Guyard, France' },
      { name: 'Hitech Pulse-Eight', points: 142, position: 6, color: '#002F6C', base: 'Silverstone, United Kingdom' },
    ],
    calendar: [
      { round: 1, gpName: 'Bahrain Grand Prix', circuit: 'Bahrain International Circuit', countryFlag: '🇧🇭', date: '28 FEB – 02 MAR', isCompleted: true, sprintWinner: 'Tuukka Taponen', featureWinner: 'Freddie Slater', polePosition: 'Freddie Slater', fastestLap: 'Freddie Slater' },
      { round: 2, gpName: 'Melbourne Grand Prix', circuit: 'Albert Park Circuit', countryFlag: '🇦🇺', date: '22 MAR – 24 MAR', isCompleted: true, sprintWinner: 'Ugo Ugochukwu', featureWinner: 'Tuukka Taponen', polePosition: 'Tuukka Taponen', fastestLap: 'Ugo Ugochukwu' },
      { round: 3, gpName: 'Imola Grand Prix', circuit: 'Autodromo Enzo e Dino Ferrari', countryFlag: '🇮🇹', date: '17 MAY – 19 MAY', isCompleted: true, sprintWinner: 'Freddie Slater', featureWinner: 'Théophile Naael', polePosition: 'Freddie Slater', fastestLap: 'Freddie Slater' },
    ],
  },
  academy: {
    seriesId: 'academy',
    seriesName: 'F1 Academy',
    championshipYear: '2026',
    description: 'Official all-female driver development series directly supported by all 10 Formula 1 teams. Single-spec Tatuus F4-T421 chassis powered by Autotecnica 1.4L Turbo engines.',
    regulations: 'Two 30-minute races per weekend. 25 pts for Race Winners, 2 pts for Pole Position, 1 pt for Fastest Lap.',
    carSpecs: {
      model: 'Tatuus F4-T421 Chassis',
      chassis: 'Carbon-fibre monocoque with FIA Halo safety device & front/rear impact structures',
      engine: 'Autotecnica 1.4L 4-Cylinder Turbocharged Engine',
      power: '174 HP @ 6,500 RPM',
      topSpeed: '240 km/h (149 mph)',
      acceleration: '0–100 km/h in 3.6 seconds',
      gearbox: 'Sadev 6-speed sequential paddle-shift gearbox',
      weight: '570 kg (minimum weight including driver)',
      tyres: 'Pirelli 13-inch bespoke F1 Academy compound tyres',
      fuel: '100% Sustainable E20 Racing Fuel',
    },
    drivers: [
      {
        id: 'pulling',
        name: 'Abbi Pulling',
        code: 'PUL',
        number: 9,
        country: 'Great Britain',
        countryFlag: '🇬🇧',
        team: 'Rodin Motorsport',
        f1Academy: 'Alpine F1 Team',
        f1AcademyColor: '#0090FF',
        points: 248,
        position: 1,
        wins: 7,
        podiums: 11,
        poles: 7,
        headshotUrl: 'https://res.cloudinary.com/prod-f2f3/c_lfill,w_300/q_auto/v1770000000/common/f1a/2026/rodin/abbpul01/2026rodinabbpul01right.webp',
        bio: 'Dominant F1 Academy Champion backed by Alpine F1 Team.',
      },
      {
        id: 'weug',
        name: 'Maya Weug',
        code: 'WEU',
        number: 64,
        country: 'Netherlands',
        countryFlag: '🇳🇱',
        team: 'MP Motorsport',
        f1Academy: 'Scuderia Ferrari HP',
        f1AcademyColor: '#E8002D',
        points: 172,
        position: 2,
        wins: 3,
        podiums: 8,
        poles: 2,
        headshotUrl: 'https://res.cloudinary.com/prod-f2f3/c_lfill,w_300/q_auto/v1770000000/common/f1a/2026/mp/mayweu01/2026mpmayweu01right.webp',
        bio: 'Ferrari Driver Academy trailblazer who claimed victories in Miami and Barcelona.',
      },
      {
        id: 'pin',
        name: 'Doriane Pin',
        code: 'PIN',
        number: 28,
        country: 'France',
        countryFlag: '🇫🇷',
        team: 'PREMA Racing',
        f1Academy: 'Mercedes-AMG PETRONAS',
        f1AcademyColor: '#27F4D2',
        points: 165,
        position: 3,
        wins: 3,
        podiums: 7,
        poles: 3,
        headshotUrl: 'https://res.cloudinary.com/prod-f2f3/c_lfill,w_300/q_auto/v1770000000/common/f1a/2026/prema/dorpin01/2026premadorpin01right.webp',
        bio: 'Iron Dames and Mercedes Junior driver with supreme endurance and single-seater pedigree.',
      },
      {
        id: 'chambers',
        name: 'Chloe Chambers',
        code: 'CHA',
        number: 14,
        country: 'United States',
        countryFlag: '🇺🇸',
        team: 'Campos Racing',
        f1Academy: 'Haas F1 Team',
        f1AcademyColor: '#E6002B',
        points: 124,
        position: 4,
        wins: 1,
        podiums: 5,
        poles: 1,
        headshotUrl: 'https://res.cloudinary.com/prod-f2f3/c_lfill,w_300/q_auto/v1770000000/common/f1a/2026/campos/chlocha01/2026camposchlocha01right.webp',
        bio: 'Haas F1 Team driver who scored a sensational race victory in Barcelona.',
      },
      {
        id: 'noda',
        name: 'Juju Noda',
        code: 'NOD',
        number: 10,
        country: 'Japan',
        countryFlag: '🇯🇵',
        team: 'Rodin Motorsport',
        f1Academy: 'Red Bull Racing',
        f1AcademyColor: '#3671C6',
        points: 98,
        position: 5,
        wins: 1,
        podiums: 4,
        poles: 0,
        headshotUrl: 'https://res.cloudinary.com/prod-f2f3/c_lfill,w_300/q_auto/v1770000000/common/f1a/2026/rodin/jujnod01/2026rodinjujnod01right.webp',
        bio: 'Japanese racing prodigy backed by Red Bull Racing.',
      },
    ],
    teams: [
      { name: 'Rodin Motorsport', points: 346, position: 1, color: '#0090FF', base: 'Farnham, United Kingdom' },
      { name: 'PREMA Racing', points: 295, position: 2, color: '#27F4D2', base: 'Grisignano di Zocco, Italy' },
      { name: 'MP Motorsport', points: 248, position: 3, color: '#E8002D', base: 'Westmaas, Netherlands' },
      { name: 'Campos Racing', points: 182, position: 4, color: '#E6002B', base: 'Alzira, Spain' },
    ],
    calendar: [
      { round: 1, gpName: 'Jeddah Grand Prix', circuit: 'Jeddah Corniche Circuit', countryFlag: '🇸🇦', date: '07 MAR – 09 MAR', isCompleted: true, sprintWinner: 'Doriane Pin', featureWinner: 'Abbi Pulling', polePosition: 'Doriane Pin', fastestLap: 'Abbi Pulling' },
      { round: 2, gpName: 'Miami Grand Prix', circuit: 'Miami International Autodrome', countryFlag: '🇺🇸', date: '03 MAY – 05 MAY', isCompleted: true, sprintWinner: 'Abbi Pulling', featureWinner: 'Maya Weug', polePosition: 'Abbi Pulling', fastestLap: 'Maya Weug' },
      { round: 3, gpName: 'Barcelona Grand Prix', circuit: 'Circuit de Barcelona-Catalunya', countryFlag: '🇪🇸', date: '21 JUN – 23 JUN', isCompleted: true, sprintWinner: 'Chloe Chambers', featureWinner: 'Abbi Pulling', polePosition: 'Abbi Pulling', fastestLap: 'Abbi Pulling' },
    ],
  },
};
