export interface JuniorDriver {
  id: string;
  name: string;
  code: string;
  number: number;
  country: string;
  countryFlag: string;
  team: string;
  f1Academy?: string; // Parent F1 team (e.g., 'ferrari', 'mercedes', 'red_bull')
  points: number;
  position: number;
  wins: number;
  podiums: number;
  poles: number;
  bio?: string;
}

export interface JuniorTeam {
  name: string;
  points: number;
  position: number;
  color: string;
}

export interface JuniorRaceWeekend {
  round: number;
  gpName: string;
  circuit: string;
  countryFlag: string;
  date: string;
  isCompleted: boolean;
  sprintWinner?: string;
  featureWinner?: string;
  polePosition?: string;
  fastestLap?: string;
}

export interface JuniorSeriesData {
  seriesId: 'f2' | 'f3' | 'academy';
  seriesName: string;
  championshipYear: string;
  description: string;
  regulations: string;
  drivers: JuniorDriver[];
  teams: JuniorTeam[];
  calendar: JuniorRaceWeekend[];
}

export const JUNIOR_SERIES_DATABASE: Record<'f2' | 'f3' | 'academy', JuniorSeriesData> = {
  f2: {
    seriesId: 'f2',
    seriesName: 'FIA Formula 2 Championship',
    championshipYear: '2024 / 2025',
    description: 'The premier feeder formula to Formula 1, racing 620bhp Dallara F2 2024 spec machinery on Grand Prix weekends.',
    regulations: 'Sprint Race (reverse top 10 on Friday qualifying) & Feature Race (mandatory pit stop).',
    drivers: [
      {
        id: 'hadjar',
        name: 'Isack Hadjar',
        code: 'HAD',
        number: 20,
        country: 'France',
        countryFlag: '🇫🇷',
        team: 'Campos Racing',
        f1Academy: 'red_bull',
        points: 165,
        position: 1,
        wins: 4,
        podiums: 7,
        poles: 1,
        bio: 'Red Bull Junior driver celebrated for aggressive tyre conservation and wet-weather mastery.',
      },
      {
        id: 'bortoleto',
        name: 'Gabriel Bortoleto',
        code: 'BOR',
        number: 10,
        country: 'Brazil',
        countryFlag: '🇧🇷',
        team: 'Invicta Racing',
        f1Academy: 'sauber',
        points: 169.5,
        position: 2,
        wins: 2,
        podiums: 5,
        poles: 2,
        bio: 'Reigning F3 champion graduated to F2 and secured 2025 F1 race seat with Kick Sauber.',
      },
      {
        id: 'aron',
        name: 'Paul Aron',
        code: 'ARO',
        number: 17,
        country: 'Estonia',
        countryFlag: '🇪🇪',
        team: 'Hitech Pulse-Eight',
        f1Academy: 'mercedes',
        points: 133,
        position: 3,
        wins: 0,
        podiums: 7,
        poles: 3,
        bio: 'Remarkably consistent rookie recording seven podium finishes in the first half of the season.',
      },
      {
        id: 'maloney',
        name: 'Zane Maloney',
        code: 'MAL',
        number: 5,
        country: 'Barbados',
        countryFlag: '🇧🇧',
        team: 'Rodin Motorsport',
        f1Academy: 'sauber',
        points: 135,
        position: 4,
        wins: 2,
        podiums: 5,
        poles: 1,
        bio: '"The Boy from Barbados" opened the campaign with an emphatic double victory in Sakhir.',
      },
      {
        id: 'crawford',
        name: 'Jak Crawford',
        code: 'CRA',
        number: 7,
        country: 'United States',
        countryFlag: '🇺🇸',
        team: 'DAMS Lucas Oil',
        f1Academy: 'aston_martin',
        points: 116,
        position: 5,
        wins: 1,
        podiums: 5,
        poles: 0,
        bio: 'Aston Martin Young Driver Development talent with race-winning pace across European circuits.',
      },
      {
        id: 'colapinto',
        name: 'Franco Colapinto',
        code: 'COL',
        number: 12,
        country: 'Argentina',
        countryFlag: '🇦🇷',
        team: 'MP Motorsport',
        f1Academy: 'williams',
        points: 96,
        position: 6,
        wins: 1,
        podiums: 3,
        poles: 0,
        bio: 'Williams Racing Academy standout who claimed Imola victory before F1 promotion.',
      },
      {
        id: 'antonelli',
        name: 'Andrea Kimi Antonelli',
        code: 'ANT',
        number: 4,
        country: 'Italy',
        countryFlag: '🇮🇹',
        team: 'PREMA Racing',
        f1Academy: 'mercedes',
        points: 113,
        position: 7,
        wins: 2,
        podiums: 3,
        poles: 0,
        bio: 'Mercedes protégé who claimed sensational wins at Silverstone (wet) and Hungaroring.',
      },
      {
        id: 'bearman',
        name: 'Oliver Bearman',
        code: 'BEA',
        number: 3,
        country: 'Great Britain',
        countryFlag: '🇬🇧',
        team: 'PREMA Racing',
        f1Academy: 'ferrari',
        points: 50,
        position: 8,
        wins: 2,
        podiums: 2,
        poles: 1,
        bio: 'Ferrari Driver Academy talent signed to Haas F1 Team for 2025.',
      },
      {
        id: 'maini',
        name: 'Kush Maini',
        code: 'MAI',
        number: 9,
        country: 'India',
        countryFlag: '🇮🇳',
        team: 'Invicta Racing',
        f1Academy: 'alpine',
        points: 74,
        position: 9,
        wins: 1,
        podiums: 5,
        poles: 1,
        bio: 'Alpine Academy reserve driver with pole positions and strong Saturday sprint performances.',
      },
      {
        id: 'marti',
        name: 'Pepe Martí',
        code: 'MAR',
        number: 21,
        country: 'Spain',
        countryFlag: '🇪🇸',
        team: 'Campos Racing',
        f1Academy: 'red_bull',
        points: 43,
        position: 10,
        wins: 0,
        podiums: 3,
        poles: 0,
        bio: 'Mentored by Fernando Alonso and backed by Red Bull Junior Team.',
      },
    ],
    teams: [
      { name: 'Invicta Racing', points: 243.5, position: 1, color: '#FCD800' },
      { name: 'Campos Racing', points: 208, position: 2, color: '#E8002D' },
      { name: 'MP Motorsport', points: 181.5, position: 3, color: '#FF8000' },
      { name: 'PREMA Racing', points: 163, position: 4, color: '#E8002D' },
      { name: 'Rodin Motorsport', points: 148, position: 5, color: '#27F4D2' },
      { name: 'Hitech Pulse-Eight', points: 147, position: 6, color: '#FFFFFF' },
    ],
    calendar: [
      { round: 1, gpName: 'Bahrain Grand Prix', circuit: 'Sakhir', countryFlag: '🇧🇭', date: 'Feb 29 - Mar 02', isCompleted: true, sprintWinner: 'Zane Maloney', featureWinner: 'Zane Maloney', polePosition: 'Gabriel Bortoleto' },
      { round: 2, gpName: 'Saudi Arabian Grand Prix', circuit: 'Jeddah Corniche', countryFlag: '🇸🇦', date: 'Mar 07 - Mar 09', isCompleted: true, sprintWinner: 'Dennis Hauger', featureWinner: 'Enzo Fittipaldi', polePosition: 'Oliver Bearman' },
      { round: 3, gpName: 'Australian Grand Prix', circuit: 'Albert Park', countryFlag: '🇦🇺', date: 'Mar 22 - Mar 24', isCompleted: true, sprintWinner: 'Roman Stanek', featureWinner: 'Isack Hadjar', polePosition: 'Dennis Hauger' },
      { round: 4, gpName: 'Emilia Romagna Grand Prix', circuit: 'Imola', countryFlag: '🇮🇹', date: 'May 17 - May 19', isCompleted: true, sprintWinner: 'Franco Colapinto', featureWinner: 'Isack Hadjar', polePosition: 'Gabriel Bortoleto' },
      { round: 5, gpName: 'Monaco Grand Prix', circuit: 'Circuit de Monaco', countryFlag: '🇲🇨', date: 'May 23 - May 26', isCompleted: true, sprintWinner: 'Taylor Barnard', featureWinner: 'Zak O\'Sullivan', polePosition: 'Richard Verschoor' },
      { round: 6, gpName: 'Spanish Grand Prix', circuit: 'Circuit de Barcelona-Catalunya', countryFlag: '🇪🇸', date: 'Jun 21 - Jun 23', isCompleted: true, sprintWinner: 'Victor Martins', featureWinner: 'Jak Crawford', polePosition: 'Paul Aron' },
      { round: 7, gpName: 'Austrian Grand Prix', circuit: 'Red Bull Ring', countryFlag: '🇦🇹', date: 'Jun 28 - Jun 30', isCompleted: true, sprintWinner: 'Oliver Bearman', featureWinner: 'Gabriel Bortoleto', polePosition: 'Dennis Hauger' },
      { round: 8, gpName: 'British Grand Prix', circuit: 'Silverstone', countryFlag: '🇬🇧', date: 'Jul 05 - Jul 07', isCompleted: true, sprintWinner: 'Andrea Kimi Antonelli', featureWinner: 'Isack Hadjar', polePosition: 'Isack Hadjar' },
      { round: 9, gpName: 'Hungarian Grand Prix', circuit: 'Hungaroring', countryFlag: '🇭🇺', date: 'Jul 19 - Jul 21', isCompleted: true, sprintWinner: 'Richard Verschoor', featureWinner: 'Andrea Kimi Antonelli', polePosition: 'Paul Aron' },
      { round: 10, gpName: 'Belgian Grand Prix', circuit: 'Spa-Francorchamps', countryFlag: '🇧🇪', date: 'Jul 26 - Jul 28', isCompleted: true, sprintWinner: 'Zak O\'Sullivan', featureWinner: 'Isack Hadjar', polePosition: 'Paul Aron' },
      { round: 11, gpName: 'Italian Grand Prix', circuit: 'Monza', countryFlag: '🇮🇹', date: 'Aug 30 - Sep 01', isCompleted: true, sprintWinner: 'Oliver Bearman', featureWinner: 'Gabriel Bortoleto', polePosition: 'Zane Maloney' },
      { round: 12, gpName: 'Azerbaijan Grand Prix', circuit: 'Baku City Circuit', countryFlag: '🇦🇿', date: 'Sep 13 - Sep 15', isCompleted: true, sprintWinner: 'Joshua Dürksen', featureWinner: 'Richard Verschoor', polePosition: 'Richard Verschoor' },
      { round: 13, gpName: 'Qatar Grand Prix', circuit: 'Lusail Circuit', countryFlag: '🇶🇦', date: 'Nov 29 - Dec 01', isCompleted: false },
      { round: 14, gpName: 'Abu Dhabi Grand Prix', circuit: 'Yas Marina Circuit', countryFlag: '🇦🇪', date: 'Dec 06 - Dec 08', isCompleted: false },
    ],
  },
  f3: {
    seriesId: 'f3',
    seriesName: 'FIA Formula 3 Championship',
    championshipYear: '2024 / 2025',
    description: 'The ultra-competitive 30-car junior category running 380bhp naturally-aspirated Mecachrome V6 engines.',
    regulations: 'Top 12 qualifying inversion for Sprint Race, full distance Feature Race on Sunday.',
    drivers: [
      {
        id: 'fornaroli',
        name: 'Leonardo Fornaroli',
        code: 'FOR',
        number: 4,
        country: 'Italy',
        countryFlag: '🇮🇹',
        team: 'Trident',
        f1Academy: 'mclaren',
        points: 153,
        position: 1,
        wins: 0,
        podiums: 7,
        poles: 2,
        bio: 'Clinched the 2024 FIA F3 Championship in a dramatic last-lap Monza overtake.',
      },
      {
        id: 'mini',
        name: 'Gabriele Minì',
        code: 'MIN',
        number: 2,
        country: 'Italy',
        countryFlag: '🇮🇹',
        team: 'PREMA Racing',
        f1Academy: 'alpine',
        points: 130,
        position: 2,
        wins: 1,
        podiums: 5,
        poles: 1,
        bio: 'Alpine Academy Italian star celebrated for qualifying dominance around street venues.',
      },
      {
        id: 'browning',
        name: 'Luke Browning',
        code: 'BRO',
        number: 14,
        country: 'Great Britain',
        countryFlag: '🇬🇧',
        team: 'Hitech Pulse-Eight',
        f1Academy: 'williams',
        points: 128,
        position: 3,
        wins: 2,
        podiums: 3,
        poles: 2,
        bio: 'Macau Grand Prix winner and Williams Racing Academy representative.',
      },
      {
        id: 'lindblad',
        name: 'Arvid Lindblad',
        code: 'LIN',
        number: 3,
        country: 'Great Britain',
        countryFlag: '🇬🇧',
        team: 'PREMA Racing',
        f1Academy: 'red_bull',
        points: 113,
        position: 4,
        wins: 4,
        podiums: 5,
        poles: 0,
        bio: 'Historic double winner at Silverstone, Red Bull Academy protégé promoted directly to F2.',
      },
      {
        id: 'beganovic',
        name: 'Dino Beganovic',
        code: 'BEG',
        number: 1,
        country: 'Sweden',
        countryFlag: '🇸🇪',
        team: 'PREMA Racing',
        f1Academy: 'ferrari',
        points: 109,
        position: 5,
        wins: 2,
        podiums: 4,
        poles: 1,
        bio: 'Ferrari Driver Academy senior junior with feature race victories in Melbourne and Spa.',
      },
      {
        id: 'boya',
        name: 'Mari Boya',
        code: 'BOY',
        number: 6,
        country: 'Spain',
        countryFlag: '🇪🇸',
        team: 'Campos Racing',
        f1Academy: 'aston_martin',
        points: 82,
        position: 6,
        wins: 1,
        podiums: 2,
        poles: 0,
        bio: 'Spanish racer taking his maiden F3 victory on home asphalt in Barcelona.',
      },
    ],
    teams: [
      { name: 'PREMA Racing', points: 352, position: 1, color: '#E8002D' },
      { name: 'Trident', points: 281, position: 2, color: '#0090FF' },
      { name: 'ART Grand Prix', points: 245, position: 3, color: '#FFFFFF' },
      { name: 'Campos Racing', points: 179, position: 4, color: '#E8002D' },
      { name: 'Hitech Pulse-Eight', points: 166, position: 5, color: '#27F4D2' },
    ],
    calendar: [
      { round: 1, gpName: 'Bahrain Grand Prix', circuit: 'Sakhir', countryFlag: '🇧🇭', date: 'Feb 29 - Mar 02', isCompleted: true, sprintWinner: 'Arvid Lindblad', featureWinner: 'Luke Browning' },
      { round: 2, gpName: 'Australian Grand Prix', circuit: 'Albert Park', countryFlag: '🇦🇺', date: 'Mar 22 - Mar 24', isCompleted: true, sprintWinner: 'Martinius Stenshorne', featureWinner: 'Dino Beganovic' },
      { round: 3, gpName: 'Emilia Romagna Grand Prix', circuit: 'Imola', countryFlag: '🇮🇹', date: 'May 17 - May 19', isCompleted: true, sprintWinner: 'Oliver Goethe', featureWinner: 'Sami Meguetounif' },
      { round: 4, gpName: 'Monaco Grand Prix', circuit: 'Circuit de Monaco', countryFlag: '🇲🇨', date: 'May 23 - May 26', isCompleted: true, sprintWinner: 'Nikola Tsolov', featureWinner: 'Gabriele Minì' },
      { round: 5, gpName: 'Spanish Grand Prix', circuit: 'Barcelona', countryFlag: '🇪🇸', date: 'Jun 21 - Jun 23', isCompleted: true, sprintWinner: 'Mari Boya', featureWinner: 'Arvid Lindblad' },
      { round: 6, gpName: 'Austrian Grand Prix', circuit: 'Red Bull Ring', countryFlag: '🇦🇹', date: 'Jun 28 - Jun 30', isCompleted: true, sprintWinner: 'Nikola Tsolov', featureWinner: 'Luke Browning' },
      { round: 7, gpName: 'British Grand Prix', circuit: 'Silverstone', countryFlag: '🇬🇧', date: 'Jul 05 - Jul 07', isCompleted: true, sprintWinner: 'Arvid Lindblad', featureWinner: 'Arvid Lindblad' },
      { round: 8, gpName: 'Hungarian Grand Prix', circuit: 'Hungaroring', countryFlag: '🇭🇺', date: 'Jul 19 - Jul 21', isCompleted: true, sprintWinner: 'Tuukka Taponen', featureWinner: 'Nikola Tsolov' },
      { round: 9, gpName: 'Belgian Grand Prix', circuit: 'Spa-Francorchamps', countryFlag: '🇧🇪', date: 'Jul 26 - Jul 28', isCompleted: true, sprintWinner: 'Dino Beganovic', featureWinner: 'Callum Voisin' },
      { round: 10, gpName: 'Italian Grand Prix', circuit: 'Monza', countryFlag: '🇮🇹', date: 'Aug 30 - Sep 01', isCompleted: true, sprintWinner: 'Tim Tramnitz', featureWinner: 'Sami Meguetounif' },
    ],
  },
  academy: {
    seriesId: 'academy',
    seriesName: 'F1 Academy',
    championshipYear: '2024 / 2025',
    description: 'Formula 1’s official all-female racing series developed to prepare young female drivers for F3, F2, and F1.',
    regulations: 'All 10 Formula 1 teams nominate and livery-sponsor one car, racing spec Tatuus F4-T421 chassis.',
    drivers: [
      {
        id: 'pulling',
        name: 'Abbi Pulling',
        code: 'PUL',
        number: 9,
        country: 'Great Britain',
        countryFlag: '🇬🇧',
        team: 'Rodin Motorsport',
        f1Academy: 'alpine',
        points: 269,
        position: 1,
        wins: 7,
        podiums: 11,
        poles: 7,
        bio: 'Dominant 2024 Champion supported by BWT Alpine F1 Team with 7 race victories.',
      },
      {
        id: 'pin',
        name: 'Doriane Pin',
        code: 'PIN',
        number: 28,
        country: 'France',
        countryFlag: '🇫🇷',
        team: 'PREMA Racing',
        f1Academy: 'mercedes',
        points: 174,
        position: 2,
        wins: 2,
        podiums: 6,
        poles: 3,
        bio: '"Pocket Rocket" backed by Mercedes-AMG F1 Team with lightning raw qualifying pace.',
      },
      {
        id: 'weug',
        name: 'Maya Weug',
        code: 'WEU',
        number: 64,
        country: 'Netherlands',
        countryFlag: '🇳🇱',
        team: 'PREMA Racing',
        f1Academy: 'ferrari',
        points: 120,
        position: 3,
        wins: 0,
        podiums: 6,
        poles: 0,
        bio: 'First female driver inducted into the prestigious Ferrari Driver Academy.',
      },
      {
        id: 'chambers',
        name: 'Chloe Chambers',
        code: 'CHA',
        number: 14,
        country: 'United States',
        countryFlag: '🇺🇸',
        team: 'Campos Racing',
        f1Academy: 'haas',
        points: 103,
        position: 4,
        wins: 1,
        podiums: 3,
        poles: 0,
        bio: 'Representing MoneyGram Haas F1 Team, took a brilliant Barcelona race victory.',
      },
      {
        id: 'bustamante',
        name: 'Bianca Bustamante',
        code: 'BUS',
        number: 16,
        country: 'Philippines',
        countryFlag: '🇵🇭',
        team: 'ART Grand Prix',
        f1Academy: 'mclaren',
        points: 57,
        position: 5,
        wins: 0,
        podiums: 1,
        poles: 0,
        bio: 'McLaren Driver Development programme talent with an immense global motorsport following.',
      },
      {
        id: 'block',
        name: 'Lia Block',
        code: 'BLO',
        number: 57,
        country: 'United States',
        countryFlag: '🇺🇸',
        team: 'ART Grand Prix',
        f1Academy: 'williams',
        points: 36,
        position: 6,
        wins: 0,
        podiums: 0,
        poles: 0,
        bio: 'Williams Racing Driver Academy member rapidly advancing in single-seater formula racing.',
      },
      {
        id: 'nobels',
        name: 'Aurelia Nobels',
        code: 'NOB',
        number: 22,
        country: 'Brazil',
        countryFlag: '🇧🇷',
        team: 'ART Grand Prix',
        f1Academy: 'ferrari',
        points: 22,
        position: 7,
        wins: 0,
        podiums: 0,
        poles: 0,
        bio: 'FIA Girls on Track Rising Stars winner supported by Ferrari Driver Academy.',
      },
      {
        id: 'hausmann',
        name: 'Tina Hausmann',
        code: 'HAU',
        number: 19,
        country: 'Switzerland',
        countryFlag: '🇨🇭',
        team: 'PREMA Racing',
        f1Academy: 'aston_martin',
        points: 17,
        position: 8,
        wins: 0,
        podiums: 0,
        poles: 0,
        bio: 'Aston Martin Aramco F1 Team nominated driver developing through European circuits.',
      },
    ],
    teams: [
      { name: 'PREMA Racing', points: 311, position: 1, color: '#E8002D' },
      { name: 'Rodin Motorsport', points: 295, position: 2, color: '#27F4D2' },
      { name: 'Campos Racing', points: 176, position: 3, color: '#E8002D' },
      { name: 'ART Grand Prix', points: 115, position: 4, color: '#0090FF' },
      { name: 'MP Motorsport', points: 94, position: 5, color: '#FF8000' },
    ],
    calendar: [
      { round: 1, gpName: 'Saudi Arabia Grand Prix', circuit: 'Jeddah Corniche', countryFlag: '🇸🇦', date: 'Mar 07 - Mar 09', isCompleted: true, sprintWinner: 'Doriane Pin', featureWinner: 'Abbi Pulling' },
      { round: 2, gpName: 'Miami Grand Prix', circuit: 'Miami International Autodrome', countryFlag: '🇺🇸', date: 'May 03 - May 05', isCompleted: true, sprintWinner: 'Abbi Pulling', featureWinner: 'Abbi Pulling' },
      { round: 3, gpName: 'Spanish Grand Prix', circuit: 'Barcelona', countryFlag: '🇪🇸', date: 'Jun 21 - Jun 23', isCompleted: true, sprintWinner: 'Abbi Pulling', featureWinner: 'Chloe Chambers' },
      { round: 4, gpName: 'Dutch Grand Prix', circuit: 'Zandvoort', countryFlag: '🇳🇱', date: 'Aug 23 - Aug 25', isCompleted: true, sprintWinner: 'Abbi Pulling', featureWinner: 'Doriane Pin' },
      { round: 5, gpName: 'Singapore Grand Prix', circuit: 'Marina Bay Street Circuit', countryFlag: '🇸🇬', date: 'Sep 20 - Sep 22', isCompleted: true, sprintWinner: 'Abbi Pulling', featureWinner: 'Abbi Pulling' },
      { round: 6, gpName: 'Qatar Grand Prix', circuit: 'Lusail Circuit', countryFlag: '🇶🇦', date: 'Nov 29 - Dec 01', isCompleted: false },
      { round: 7, gpName: 'Abu Dhabi Grand Prix', circuit: 'Yas Marina Circuit', countryFlag: '🇦🇪', date: 'Dec 06 - Dec 08', isCompleted: false },
    ],
  },
};

/**
 * Get all academy drivers affiliated with a given F1 team id
 */
export function getAcademyDriversForTeam(teamId: string): JuniorDriver[] {
  const normalized = teamId.toLowerCase().replace(/[\s-]+/g, '_');
  const allDrivers = [
    ...JUNIOR_SERIES_DATABASE.f2.drivers,
    ...JUNIOR_SERIES_DATABASE.f3.drivers,
    ...JUNIOR_SERIES_DATABASE.academy.drivers,
  ];

  return allDrivers.filter((d) => d.f1Academy === normalized);
}
