import { F1_TEAMS } from './teams';

export interface PitStopRecord {
  id: string;
  driverId: string;
  driverName: string;
  driverCode: string;
  teamId: string;
  teamName: string;
  round: number;
  gpName: string;
  lap: number;
  stopNumber: number;
  stationaryTime: number; // in seconds (e.g., 1.90)
  pitLaneTime: number;    // total lane time (e.g., 21.4)
  date: string;
}

export interface TeamPitCrewRanking {
  teamId: string;
  teamName: string;
  color: string;
  dhlPoints: number;
  averageStationaryTime: number;
  fastestStop: number;
  sub25StopsCount: number;
  totalStops: number;
}

export const TOP_SEASON_PIT_STOPS: PitStopRecord[] = [
  {
    id: 'ps-1',
    driverId: 'max_verstappen',
    driverName: 'Max Verstappen',
    driverCode: 'VER',
    teamId: 'red_bull',
    teamName: 'Red Bull Racing',
    round: 5,
    gpName: 'Chinese Grand Prix (Shanghai)',
    lap: 13,
    stopNumber: 1,
    stationaryTime: 1.90,
    pitLaneTime: 21.32,
    date: 'Apr 21, 2024',
  },
  {
    id: 'ps-2',
    driverId: 'norris',
    driverName: 'Lando Norris',
    driverCode: 'NOR',
    teamId: 'mclaren',
    teamName: 'McLaren',
    round: 15,
    gpName: 'Dutch Grand Prix (Zandvoort)',
    lap: 28,
    stopNumber: 1,
    stationaryTime: 1.95,
    pitLaneTime: 20.89,
    date: 'Aug 25, 2024',
  },
  {
    id: 'ps-3',
    driverId: 'perez',
    driverName: 'Sergio Perez',
    driverCode: 'PER',
    teamId: 'red_bull',
    teamName: 'Red Bull Racing',
    round: 5,
    gpName: 'Chinese Grand Prix (Shanghai)',
    lap: 13,
    stopNumber: 1,
    stationaryTime: 2.00,
    pitLaneTime: 21.45,
    date: 'Apr 21, 2024',
  },
  {
    id: 'ps-4',
    driverId: 'piastri',
    driverName: 'Oscar Piastri',
    driverCode: 'PIA',
    teamId: 'mclaren',
    teamName: 'McLaren',
    round: 14,
    gpName: 'Belgian Grand Prix (Spa)',
    lap: 11,
    stopNumber: 1,
    stationaryTime: 2.02,
    pitLaneTime: 22.10,
    date: 'Jul 28, 2024',
  },
  {
    id: 'ps-5',
    driverId: 'russell',
    driverName: 'George Russell',
    driverCode: 'RUS',
    teamId: 'mercedes',
    teamName: 'Mercedes',
    round: 12,
    gpName: 'British Grand Prix (Silverstone)',
    lap: 18,
    stopNumber: 1,
    stationaryTime: 2.09,
    pitLaneTime: 24.15,
    date: 'Jul 07, 2024',
  },
  {
    id: 'ps-6',
    driverId: 'leclerc',
    driverName: 'Charles Leclerc',
    driverCode: 'LEC',
    teamId: 'ferrari',
    teamName: 'Ferrari',
    round: 14,
    gpName: 'Belgian Grand Prix (Spa)',
    lap: 12,
    stopNumber: 1,
    stationaryTime: 2.14,
    pitLaneTime: 22.25,
    date: 'Jul 28, 2024',
  },
  {
    id: 'ps-7',
    driverId: 'sainz',
    driverName: 'Carlos Sainz',
    driverCode: 'SAI',
    teamId: 'ferrari',
    teamName: 'Ferrari',
    round: 3,
    gpName: 'Australian Grand Prix (Melbourne)',
    lap: 16,
    stopNumber: 1,
    stationaryTime: 2.18,
    pitLaneTime: 21.65,
    date: 'Mar 24, 2024',
  },
  {
    id: 'ps-8',
    driverId: 'albon',
    driverName: 'Alex Albon',
    driverCode: 'ALB',
    teamId: 'williams',
    teamName: 'Williams',
    round: 4,
    gpName: 'Japanese Grand Prix (Suzuka)',
    lap: 15,
    stopNumber: 1,
    stationaryTime: 2.19,
    pitLaneTime: 23.05,
    date: 'Apr 07, 2024',
  },
  {
    id: 'ps-9',
    driverId: 'alonso',
    driverName: 'Fernando Alonso',
    driverCode: 'ALO',
    teamId: 'aston_martin',
    teamName: 'Aston Martin',
    round: 10,
    gpName: 'Spanish Grand Prix (Barcelona)',
    lap: 19,
    stopNumber: 1,
    stationaryTime: 2.21,
    pitLaneTime: 22.88,
    date: 'Jun 23, 2024',
  },
  {
    id: 'ps-10',
    driverId: 'tsunoda',
    driverName: 'Yuki Tsunoda',
    driverCode: 'TSU',
    teamId: 'rb',
    teamName: 'Racing Bulls',
    round: 8,
    gpName: 'Monaco Grand Prix (Monte Carlo)',
    lap: 1,
    stopNumber: 1,
    stationaryTime: 2.24,
    pitLaneTime: 24.50,
    date: 'May 26, 2024',
  },
];

export const TEAM_PIT_CREW_STANDINGS: TeamPitCrewRanking[] = [
  {
    teamId: 'red_bull',
    teamName: 'Red Bull Racing',
    color: '#3671C6',
    dhlPoints: 374,
    averageStationaryTime: 2.31,
    fastestStop: 1.90,
    sub25StopsCount: 29,
    totalStops: 42,
  },
  {
    teamId: 'mclaren',
    teamName: 'McLaren',
    color: '#FF8000',
    dhlPoints: 341,
    averageStationaryTime: 2.34,
    fastestStop: 1.95,
    sub25StopsCount: 26,
    totalStops: 40,
  },
  {
    teamId: 'ferrari',
    teamName: 'Ferrari',
    color: '#E8002D',
    dhlPoints: 298,
    averageStationaryTime: 2.41,
    fastestStop: 2.14,
    sub25StopsCount: 22,
    totalStops: 39,
  },
  {
    teamId: 'mercedes',
    teamName: 'Mercedes',
    color: '#27F4D2',
    dhlPoints: 235,
    averageStationaryTime: 2.48,
    fastestStop: 2.09,
    sub25StopsCount: 18,
    totalStops: 41,
  },
  {
    teamId: 'aston_martin',
    teamName: 'Aston Martin',
    color: '#229971',
    dhlPoints: 172,
    averageStationaryTime: 2.56,
    fastestStop: 2.21,
    sub25StopsCount: 14,
    totalStops: 38,
  },
  {
    teamId: 'williams',
    teamName: 'Williams',
    color: '#64C4FF',
    dhlPoints: 124,
    averageStationaryTime: 2.62,
    fastestStop: 2.19,
    sub25StopsCount: 11,
    totalStops: 37,
  },
  {
    teamId: 'rb',
    teamName: 'Racing Bulls',
    color: '#6692FF',
    dhlPoints: 115,
    averageStationaryTime: 2.65,
    fastestStop: 2.24,
    sub25StopsCount: 9,
    totalStops: 36,
  },
  {
    teamId: 'alpine',
    teamName: 'Alpine',
    color: '#0090FF',
    dhlPoints: 86,
    averageStationaryTime: 2.74,
    fastestStop: 2.27,
    sub25StopsCount: 7,
    totalStops: 35,
  },
  {
    teamId: 'haas',
    teamName: 'Haas',
    color: '#E6002B',
    dhlPoints: 58,
    averageStationaryTime: 2.82,
    fastestStop: 2.38,
    sub25StopsCount: 5,
    totalStops: 36,
  },
  {
    teamId: 'sauber',
    teamName: 'Kick Sauber',
    color: '#52E252',
    dhlPoints: 24,
    averageStationaryTime: 3.42,
    fastestStop: 2.44,
    sub25StopsCount: 2,
    totalStops: 34,
  },
];
