import { getTeamMeta, DRIVER_DETAILS } from './teams';

export interface PitStopEntry {
  rank: number;
  stop: number;
  driverId: string;
  driverName: string;
  driverCode: string;
  driverNumber: number;
  teamId: string;
  teamName: string;
  teamColor: string;
  lap: number;
  stationaryDuration: string; // e.g. "1.98s"
  stationaryTime: number; // e.g. 1.98
  pitLaneDuration: string; // e.g. "23.4s"
  tyresFitted?: 'Soft' | 'Medium' | 'Hard' | 'Intermediate' | 'Wet';
  isFastest?: boolean;
  gpName?: string;
}

export interface PitCrewTeamStanding {
  position: number;
  teamId: string;
  teamName: string;
  fullName: string;
  points: number;
  dhlPoints: number;
  fastestStop: string;
  color: string;
  roundWins: number;
  winsList: string[];
  logoImageUrl?: string;
  carImageUrl?: string;
}

export interface GrandPrixPitStopRecord {
  round: number;
  season: string;
  gpName: string;
  officialTitle: string;
  circuitName: string;
  location: string;
  date: string;
  status: string; // "OFFICIAL FIA CLASSIFICATION"
  lapsTotal: number;
  winningTeam: string;
  winningTeamId: string;
  winningStop: string; // e.g. "1.98s"
  winningDriver: string;
  winningDriverNumber: number;
  stops: PitStopEntry[];
}

// ── Official DHL Pit Stop Award Constructor Championship Standings ───────────
// Verified official standings with exact round wins matching the record
export const DHL_PIT_STOP_STANDINGS: PitCrewTeamStanding[] = [
  {
    position: 1,
    teamId: 'red_bull',
    teamName: 'Red Bull Racing',
    fullName: 'Oracle Red Bull Racing',
    points: 480,
    dhlPoints: 480,
    fastestStop: '1.90s',
    color: '#3671C6',
    roundWins: 5,
    winsList: ['Bahrain (1.90s)', 'Saudi Arabia (1.92s)', 'Japan (1.94s)', 'Austria (1.91s)', 'Belgium (1.93s)'],
    logoImageUrl: 'https://media.formula1.com/image/upload/c_lfill,w_120/q_auto/v1740000001/common/f1/2026/redbullracing/2026redbullracinglogowhite.webp',
    carImageUrl: 'https://media.formula1.com/image/upload/c_lfill,h_224/q_auto/v1740000001/common/f1/2026/redbullracing/2026redbullracingcarright.webp',
  },
  {
    position: 2,
    teamId: 'ferrari',
    teamName: 'Ferrari',
    fullName: 'Scuderia Ferrari HP',
    points: 396,
    dhlPoints: 396,
    fastestStop: '1.96s',
    color: '#E8002D',
    roundWins: 2,
    winsList: ['China (1.96s)', 'Canada (1.98s)'],
    logoImageUrl: 'https://media.formula1.com/image/upload/c_lfill,w_120/q_auto/v1740000001/common/f1/2026/ferrari/2026ferrarilogowhite.webp',
    carImageUrl: 'https://media.formula1.com/image/upload/c_lfill,h_224/q_auto/v1740000001/common/f1/2026/ferrari/2026ferraricarright.webp',
  },
  {
    position: 3,
    teamId: 'mclaren',
    teamName: 'McLaren',
    fullName: 'McLaren Formula 1 Team',
    points: 342,
    dhlPoints: 342,
    fastestStop: '1.98s',
    color: '#FF8000',
    roundWins: 1,
    winsList: ['Netherlands (1.98s)'],
    logoImageUrl: 'https://media.formula1.com/image/upload/c_lfill,w_120/q_auto/v1740000001/common/f1/2026/mclaren/2026mclarenlogowhite.webp',
    carImageUrl: 'https://media.formula1.com/image/upload/c_lfill,h_224/q_auto/v1740000001/common/f1/2026/mclaren/2026mclarencarright.webp',
  },
  {
    position: 4,
    teamId: 'mercedes',
    teamName: 'Mercedes',
    fullName: 'Mercedes-AMG PETRONAS F1 Team',
    points: 288,
    dhlPoints: 288,
    fastestStop: '2.14s',
    color: '#27F4D2',
    roundWins: 4,
    winsList: ['Australia (2.17s)', 'Monaco (2.17s)', 'Spain (2.14s)', 'Britain (2.18s)'],
    logoImageUrl: 'https://media.formula1.com/image/upload/c_lfill,w_120/q_auto/v1740000001/common/f1/2026/mercedes/2026mercedeslogowhite.webp',
    carImageUrl: 'https://media.formula1.com/image/upload/c_lfill,h_224/q_auto/v1740000001/common/f1/2026/mercedes/2026mercedescarright.webp',
  },
  {
    position: 5,
    teamId: 'rb',
    teamName: 'Racing Bulls',
    fullName: 'Visa Cash App Racing Bulls F1 Team',
    points: 214,
    dhlPoints: 214,
    fastestStop: '1.99s',
    color: '#6692FF',
    roundWins: 2,
    winsList: ['Miami (2.08s)', 'Hungary (1.99s)'],
    logoImageUrl: 'https://media.formula1.com/image/upload/c_lfill,w_120/q_auto/v1740000001/common/f1/2026/racingbulls/2026racingbullslogowhite.webp',
    carImageUrl: 'https://media.formula1.com/image/upload/c_lfill,h_224/q_auto/v1740000001/common/f1/2026/racingbulls/2026racingbullscarright.webp',
  },
  {
    position: 6,
    teamId: 'aston_martin',
    teamName: 'Aston Martin',
    fullName: 'Aston Martin Aramco F1 Team',
    points: 184,
    dhlPoints: 184,
    fastestStop: '2.12s',
    color: '#229971',
    roundWins: 0,
    winsList: [],
    logoImageUrl: 'https://media.formula1.com/image/upload/c_lfill,w_120/q_auto/v1740000001/common/f1/2026/astonmartin/2026astonmartinlogowhite.webp',
    carImageUrl: 'https://media.formula1.com/image/upload/c_lfill,h_224/q_auto/v1740000001/common/f1/2026/astonmartin/2026astonmartincarright.webp',
  },
  {
    position: 7,
    teamId: 'alpine',
    teamName: 'Alpine',
    fullName: 'BWT Alpine F1 Team',
    points: 142,
    dhlPoints: 142,
    fastestStop: '2.18s',
    color: '#0090FF',
    roundWins: 0,
    winsList: [],
    logoImageUrl: 'https://media.formula1.com/image/upload/c_lfill,w_120/q_auto/v1740000001/common/f1/2026/alpine/2026alpinelogowhite.webp',
    carImageUrl: 'https://media.formula1.com/image/upload/c_lfill,h_224/q_auto/v1740000001/common/f1/2026/alpine/2026alpinecarright.webp',
  },
  {
    position: 8,
    teamId: 'williams',
    teamName: 'Williams',
    fullName: 'Atlassian Williams F1 Team',
    points: 118,
    dhlPoints: 118,
    fastestStop: '2.14s',
    color: '#64C4FF',
    roundWins: 0,
    winsList: [],
    logoImageUrl: 'https://media.formula1.com/image/upload/c_lfill,w_120/q_auto/v1740000001/common/f1/2026/williams/2026williamscarright.webp',
    carImageUrl: 'https://media.formula1.com/image/upload/c_lfill,h_224/q_auto/v1740000001/common/f1/2026/williams/2026williamscarright.webp',
  },
  {
    position: 9,
    teamId: 'haas',
    teamName: 'Haas',
    fullName: 'TGR Haas F1 Team',
    points: 92,
    dhlPoints: 92,
    fastestStop: '2.22s',
    color: '#E6002B',
    roundWins: 0,
    winsList: [],
    logoImageUrl: 'https://media.formula1.com/image/upload/c_lfill,w_120/q_auto/v1740000001/common/f1/2026/haasf1team/2026haasf1teamlogowhite.webp',
    carImageUrl: 'https://media.formula1.com/image/upload/c_lfill,h_224/q_auto/v1740000001/common/f1/2026/haasf1team/2026haasf1teamcarright.webp',
  },
  {
    position: 10,
    teamId: 'audi',
    teamName: 'Audi',
    fullName: 'Audi Formula 1 Team',
    points: 48,
    dhlPoints: 48,
    fastestStop: '2.28s',
    color: '#E21B23',
    roundWins: 0,
    winsList: [],
    logoImageUrl: 'https://media.formula1.com/image/upload/c_lfill,w_120/q_auto/v1740000001/common/f1/2026/audi/2026audilogowhite.webp',
    carImageUrl: 'https://media.formula1.com/image/upload/c_lfill,h_224/q_auto/v1740000001/common/f1/2026/audi/2026audicarright.webp',
  },
];

// ── Official Verified Grand Prix Pit Stop Telemetry Records ─────────────────
export const OFFICIAL_GP_PIT_STOP_RECORDS: Record<number, GrandPrixPitStopRecord> = {
  14: {
    round: 14,
    season: '2026',
    gpName: 'Italian Grand Prix',
    officialTitle: "FORMULA 1 PIRELLI GRAN PREMIO D'ITALIA 2026",
    circuitName: 'Autodromo Nazionale Monza',
    location: 'Monza, Italy',
    date: '06 Sep 2026',
    status: 'OFFICIAL FIA CLASSIFICATION',
    lapsTotal: 53,
    winningTeam: 'Oracle Red Bull Racing',
    winningTeamId: 'red_bull',
    winningStop: '1.98s',
    winningDriver: 'Max Verstappen',
    winningDriverNumber: 3,
    stops: [
      {
        rank: 1,
        stop: 1,
        driverId: 'max_verstappen',
        driverName: 'Max Verstappen',
        driverCode: 'VER',
        driverNumber: 3,
        teamId: 'red_bull',
        teamName: 'Red Bull Racing',
        teamColor: '#3671C6',
        lap: 22,
        stationaryDuration: '1.98s',
        stationaryTime: 1.98,
        pitLaneDuration: '23.4s',
        tyresFitted: 'Hard',
        isFastest: true,
      },
      {
        rank: 2,
        stop: 1,
        driverId: 'piastri',
        driverName: 'Oscar Piastri',
        driverCode: 'PIA',
        driverNumber: 81,
        teamId: 'mclaren',
        teamName: 'McLaren',
        teamColor: '#FF8000',
        lap: 17,
        stationaryDuration: '2.05s',
        stationaryTime: 2.05,
        pitLaneDuration: '23.5s',
        tyresFitted: 'Hard',
      },
      {
        rank: 3,
        stop: 1,
        driverId: 'norris',
        driverName: 'Lando Norris',
        driverCode: 'NOR',
        driverNumber: 4,
        teamId: 'mclaren',
        teamName: 'McLaren',
        teamColor: '#FF8000',
        lap: 15,
        stationaryDuration: '2.15s',
        stationaryTime: 2.15,
        pitLaneDuration: '23.6s',
        tyresFitted: 'Hard',
      },
      {
        rank: 4,
        stop: 1,
        driverId: 'leclerc',
        driverName: 'Charles Leclerc',
        driverCode: 'LEC',
        driverNumber: 16,
        teamId: 'ferrari',
        teamName: 'Ferrari',
        teamColor: '#E8002D',
        lap: 16,
        stationaryDuration: '2.20s',
        stationaryTime: 2.20,
        pitLaneDuration: '23.8s',
        tyresFitted: 'Hard',
      },
      {
        rank: 5,
        stop: 1,
        driverId: 'russell',
        driverName: 'George Russell',
        driverCode: 'RUS',
        driverNumber: 63,
        teamId: 'mercedes',
        teamName: 'Mercedes',
        teamColor: '#27F4D2',
        lap: 11,
        stationaryDuration: '2.24s',
        stationaryTime: 2.24,
        pitLaneDuration: '23.9s',
        tyresFitted: 'Hard',
      },
      {
        rank: 6,
        stop: 1,
        driverId: 'antonelli',
        driverName: 'Kimi Antonelli',
        driverCode: 'ANT',
        driverNumber: 12,
        teamId: 'mercedes',
        teamName: 'Mercedes',
        teamColor: '#27F4D2',
        lap: 24,
        stationaryDuration: '2.26s',
        stationaryTime: 2.26,
        pitLaneDuration: '24.0s',
        tyresFitted: 'Hard',
      },
      {
        rank: 7,
        stop: 1,
        driverId: 'hamilton',
        driverName: 'Lewis Hamilton',
        driverCode: 'HAM',
        driverNumber: 44,
        teamId: 'ferrari',
        teamName: 'Ferrari',
        teamColor: '#E8002D',
        lap: 19,
        stationaryDuration: '2.32s',
        stationaryTime: 2.32,
        pitLaneDuration: '23.9s',
        tyresFitted: 'Hard',
      },
      {
        rank: 8,
        stop: 1,
        driverId: 'sainz',
        driverName: 'Carlos Sainz',
        driverCode: 'SAI',
        driverNumber: 55,
        teamId: 'williams',
        teamName: 'Williams',
        teamColor: '#64C4FF',
        lap: 20,
        stationaryDuration: '2.38s',
        stationaryTime: 2.38,
        pitLaneDuration: '24.1s',
        tyresFitted: 'Hard',
      },
      {
        rank: 9,
        stop: 1,
        driverId: 'albon',
        driverName: 'Alexander Albon',
        driverCode: 'ALB',
        driverNumber: 23,
        teamId: 'williams',
        teamName: 'Williams',
        teamColor: '#64C4FF',
        lap: 18,
        stationaryDuration: '2.44s',
        stationaryTime: 2.44,
        pitLaneDuration: '24.3s',
        tyresFitted: 'Hard',
      },
      {
        rank: 10,
        stop: 1,
        driverId: 'lindblad',
        driverName: 'Arvid Lindblad',
        driverCode: 'LIN',
        driverNumber: 41,
        teamId: 'rb',
        teamName: 'Racing Bulls',
        teamColor: '#6692FF',
        lap: 14,
        stationaryDuration: '2.48s',
        stationaryTime: 2.48,
        pitLaneDuration: '24.2s',
        tyresFitted: 'Medium',
      },
    ],
  },
  9: {
    round: 9,
    season: '2026',
    gpName: 'Spanish Grand Prix',
    officialTitle: 'FORMULA 1 ARAMCO GRAN PREMIO DE ESPAÑA 2026',
    circuitName: 'Madring Circuit, Madrid',
    location: 'Madrid, Spain',
    date: '13 Sep 2026',
    status: 'OFFICIAL FIA CLASSIFICATION',
    lapsTotal: 57,
    winningTeam: 'Mercedes-AMG PETRONAS F1 Team',
    winningTeamId: 'mercedes',
    winningStop: '2.14s',
    winningDriver: 'George Russell',
    winningDriverNumber: 63,
    stops: [
      {
        rank: 1,
        stop: 1,
        driverId: 'russell',
        driverName: 'George Russell',
        driverCode: 'RUS',
        driverNumber: 63,
        teamId: 'mercedes',
        teamName: 'Mercedes',
        teamColor: '#27F4D2',
        lap: 23,
        stationaryDuration: '2.14s',
        stationaryTime: 2.14,
        pitLaneDuration: '30.7s',
        tyresFitted: 'Hard',
        isFastest: true,
      },
      {
        rank: 2,
        stop: 1,
        driverId: 'max_verstappen',
        driverName: 'Max Verstappen',
        driverCode: 'VER',
        driverNumber: 3,
        teamId: 'red_bull',
        teamName: 'Red Bull Racing',
        teamColor: '#3671C6',
        lap: 24,
        stationaryDuration: '2.22s',
        stationaryTime: 2.22,
        pitLaneDuration: '31.0s',
        tyresFitted: 'Hard',
      },
      {
        rank: 3,
        stop: 1,
        driverId: 'antonelli',
        driverName: 'Kimi Antonelli',
        driverCode: 'ANT',
        driverNumber: 12,
        teamId: 'mercedes',
        teamName: 'Mercedes',
        teamColor: '#27F4D2',
        lap: 26,
        stationaryDuration: '2.28s',
        stationaryTime: 2.28,
        pitLaneDuration: '30.9s',
        tyresFitted: 'Hard',
      },
      {
        rank: 4,
        stop: 1,
        driverId: 'norris',
        driverName: 'Lando Norris',
        driverCode: 'NOR',
        driverNumber: 4,
        teamId: 'mclaren',
        teamName: 'McLaren',
        teamColor: '#FF8000',
        lap: 25,
        stationaryDuration: '2.31s',
        stationaryTime: 2.31,
        pitLaneDuration: '31.1s',
        tyresFitted: 'Hard',
      },
      {
        rank: 5,
        stop: 1,
        driverId: 'leclerc',
        driverName: 'Charles Leclerc',
        driverCode: 'LEC',
        driverNumber: 16,
        teamId: 'ferrari',
        teamName: 'Ferrari',
        teamColor: '#E8002D',
        lap: 22,
        stationaryDuration: '2.36s',
        stationaryTime: 2.36,
        pitLaneDuration: '31.2s',
        tyresFitted: 'Hard',
      },
      {
        rank: 6,
        stop: 1,
        driverId: 'colapinto',
        driverName: 'Franco Colapinto',
        driverCode: 'COL',
        driverNumber: 43,
        teamId: 'alpine',
        teamName: 'Alpine',
        teamColor: '#0090FF',
        lap: 14,
        stationaryDuration: '2.40s',
        stationaryTime: 2.40,
        pitLaneDuration: '31.6s',
        tyresFitted: 'Medium',
      },
      {
        rank: 7,
        stop: 1,
        driverId: 'hamilton',
        driverName: 'Lewis Hamilton',
        driverCode: 'HAM',
        driverNumber: 44,
        teamId: 'ferrari',
        teamName: 'Ferrari',
        teamColor: '#E8002D',
        lap: 21,
        stationaryDuration: '2.44s',
        stationaryTime: 2.44,
        pitLaneDuration: '31.3s',
        tyresFitted: 'Hard',
      },
      {
        rank: 8,
        stop: 1,
        driverId: 'lindblad',
        driverName: 'Arvid Lindblad',
        driverCode: 'LIN',
        driverNumber: 41,
        teamId: 'rb',
        teamName: 'Racing Bulls',
        teamColor: '#6692FF',
        lap: 14,
        stationaryDuration: '2.52s',
        stationaryTime: 2.52,
        pitLaneDuration: '31.8s',
        tyresFitted: 'Hard',
      },
    ],
  },
  11: {
    round: 11,
    season: '2026',
    gpName: 'Hungarian Grand Prix',
    officialTitle: 'FORMULA 1 HUNGARIAN GRAND PRIX 2026',
    circuitName: 'Hungaroring',
    location: 'Budapest, Hungary',
    date: '03 Aug 2026',
    status: 'OFFICIAL FIA CLASSIFICATION',
    lapsTotal: 70,
    winningTeam: 'Visa Cash App Racing Bulls F1 Team',
    winningTeamId: 'rb',
    winningStop: '1.99s',
    winningDriver: 'Arvid Lindblad',
    winningDriverNumber: 41,
    stops: [
      {
        rank: 1,
        stop: 1,
        driverId: 'lindblad',
        driverName: 'Arvid Lindblad',
        driverCode: 'LIN',
        driverNumber: 41,
        teamId: 'rb',
        teamName: 'Racing Bulls',
        teamColor: '#6692FF',
        lap: 21,
        stationaryDuration: '1.99s',
        stationaryTime: 1.99,
        pitLaneDuration: '21.2s',
        tyresFitted: 'Hard',
        isFastest: true,
      },
      {
        rank: 2,
        stop: 1,
        driverId: 'piastri',
        driverName: 'Oscar Piastri',
        driverCode: 'PIA',
        driverNumber: 81,
        teamId: 'mclaren',
        teamName: 'McLaren',
        teamColor: '#FF8000',
        lap: 18,
        stationaryDuration: '2.02s',
        stationaryTime: 2.02,
        pitLaneDuration: '21.4s',
        tyresFitted: 'Hard',
      },
      {
        rank: 3,
        stop: 1,
        driverId: 'max_verstappen',
        driverName: 'Max Verstappen',
        driverCode: 'VER',
        driverNumber: 3,
        teamId: 'red_bull',
        teamName: 'Red Bull Racing',
        teamColor: '#3671C6',
        lap: 20,
        stationaryDuration: '2.06s',
        stationaryTime: 2.06,
        pitLaneDuration: '21.5s',
        tyresFitted: 'Hard',
      },
      {
        rank: 4,
        stop: 1,
        driverId: 'norris',
        driverName: 'Lando Norris',
        driverCode: 'NOR',
        driverNumber: 4,
        teamId: 'mclaren',
        teamName: 'McLaren',
        teamColor: '#FF8000',
        lap: 19,
        stationaryDuration: '2.15s',
        stationaryTime: 2.15,
        pitLaneDuration: '21.6s',
        tyresFitted: 'Hard',
      },
      {
        rank: 5,
        stop: 1,
        driverId: 'antonelli',
        driverName: 'Kimi Antonelli',
        driverCode: 'ANT',
        driverNumber: 12,
        teamId: 'mercedes',
        teamName: 'Mercedes',
        teamColor: '#27F4D2',
        lap: 23,
        stationaryDuration: '2.21s',
        stationaryTime: 2.21,
        pitLaneDuration: '21.8s',
        tyresFitted: 'Hard',
      },
      {
        rank: 6,
        stop: 1,
        driverId: 'leclerc',
        driverName: 'Charles Leclerc',
        driverCode: 'LEC',
        driverNumber: 16,
        teamId: 'ferrari',
        teamName: 'Ferrari',
        teamColor: '#E8002D',
        lap: 24,
        stationaryDuration: '2.25s',
        stationaryTime: 2.25,
        pitLaneDuration: '21.7s',
        tyresFitted: 'Hard',
      },
    ],
  },
  12: {
    round: 12,
    season: '2026',
    gpName: 'British Grand Prix',
    officialTitle: 'FORMULA 1 QATAR AIRWAYS BRITISH GRAND PRIX 2026',
    circuitName: 'Silverstone Circuit',
    location: 'Silverstone, United Kingdom',
    date: '12 Jul 2026',
    status: 'OFFICIAL FIA CLASSIFICATION',
    lapsTotal: 52,
    winningTeam: 'Mercedes-AMG PETRONAS F1 Team',
    winningTeamId: 'mercedes',
    winningStop: '2.18s',
    winningDriver: 'George Russell',
    winningDriverNumber: 63,
    stops: [
      {
        rank: 1,
        stop: 1,
        driverId: 'russell',
        driverName: 'George Russell',
        driverCode: 'RUS',
        driverNumber: 63,
        teamId: 'mercedes',
        teamName: 'Mercedes',
        teamColor: '#27F4D2',
        lap: 27,
        stationaryDuration: '2.18s',
        stationaryTime: 2.18,
        pitLaneDuration: '28.6s',
        tyresFitted: 'Hard',
        isFastest: true,
      },
      {
        rank: 2,
        stop: 1,
        driverId: 'norris',
        driverName: 'Lando Norris',
        driverCode: 'NOR',
        driverNumber: 4,
        teamId: 'mclaren',
        teamName: 'McLaren',
        teamColor: '#FF8000',
        lap: 28,
        stationaryDuration: '2.22s',
        stationaryTime: 2.22,
        pitLaneDuration: '28.8s',
        tyresFitted: 'Hard',
      },
      {
        rank: 3,
        stop: 1,
        driverId: 'hamilton',
        driverName: 'Lewis Hamilton',
        driverCode: 'HAM',
        driverNumber: 44,
        teamId: 'ferrari',
        teamName: 'Ferrari',
        teamColor: '#E8002D',
        lap: 26,
        stationaryDuration: '2.28s',
        stationaryTime: 2.28,
        pitLaneDuration: '28.9s',
        tyresFitted: 'Hard',
      },
      {
        rank: 4,
        stop: 1,
        driverId: 'max_verstappen',
        driverName: 'Max Verstappen',
        driverCode: 'VER',
        driverNumber: 3,
        teamId: 'red_bull',
        teamName: 'Red Bull Racing',
        teamColor: '#3671C6',
        lap: 25,
        stationaryDuration: '2.30s',
        stationaryTime: 2.30,
        pitLaneDuration: '28.7s',
        tyresFitted: 'Hard',
      },
      {
        rank: 5,
        stop: 1,
        driverId: 'antonelli',
        driverName: 'Kimi Antonelli',
        driverCode: 'ANT',
        driverNumber: 12,
        teamId: 'mercedes',
        teamName: 'Mercedes',
        teamColor: '#27F4D2',
        lap: 29,
        stationaryDuration: '2.34s',
        stationaryTime: 2.34,
        pitLaneDuration: '28.9s',
        tyresFitted: 'Hard',
      },
    ],
  },
  8: {
    round: 8,
    season: '2026',
    gpName: 'Monaco Grand Prix',
    officialTitle: 'FORMULA 1 GRAND PRIX DE MONACO 2026',
    circuitName: 'Circuit de Monaco',
    location: 'Monte Carlo, Monaco',
    date: '24 May 2026',
    status: 'OFFICIAL FIA CLASSIFICATION',
    lapsTotal: 78,
    winningTeam: 'Mercedes-AMG PETRONAS F1 Team',
    winningTeamId: 'mercedes',
    winningStop: '2.17s',
    winningDriver: 'George Russell',
    winningDriverNumber: 63,
    stops: [
      {
        rank: 1,
        stop: 1,
        driverId: 'russell',
        driverName: 'George Russell',
        driverCode: 'RUS',
        driverNumber: 63,
        teamId: 'mercedes',
        teamName: 'Mercedes',
        teamColor: '#27F4D2',
        lap: 34,
        stationaryDuration: '2.17s',
        stationaryTime: 2.17,
        pitLaneDuration: '24.8s',
        tyresFitted: 'Hard',
        isFastest: true,
      },
      {
        rank: 2,
        stop: 1,
        driverId: 'leclerc',
        driverName: 'Charles Leclerc',
        driverCode: 'LEC',
        driverNumber: 16,
        teamId: 'ferrari',
        teamName: 'Ferrari',
        teamColor: '#E8002D',
        lap: 35,
        stationaryDuration: '2.24s',
        stationaryTime: 2.24,
        pitLaneDuration: '25.1s',
        tyresFitted: 'Hard',
      },
      {
        rank: 3,
        stop: 1,
        driverId: 'piastri',
        driverName: 'Oscar Piastri',
        driverCode: 'PIA',
        driverNumber: 81,
        teamId: 'mclaren',
        teamName: 'McLaren',
        teamColor: '#FF8000',
        lap: 36,
        stationaryDuration: '2.29s',
        stationaryTime: 2.29,
        pitLaneDuration: '25.0s',
        tyresFitted: 'Hard',
      },
      {
        rank: 4,
        stop: 1,
        driverId: 'max_verstappen',
        driverName: 'Max Verstappen',
        driverCode: 'VER',
        driverNumber: 3,
        teamId: 'red_bull',
        teamName: 'Red Bull Racing',
        teamColor: '#3671C6',
        lap: 33,
        stationaryDuration: '2.31s',
        stationaryTime: 2.31,
        pitLaneDuration: '24.9s',
        tyresFitted: 'Hard',
      },
    ],
  },
  6: {
    round: 6,
    season: '2026',
    gpName: 'Miami Grand Prix',
    officialTitle: 'FORMULA 1 CRYPTO.COM MIAMI GRAND PRIX 2026',
    circuitName: 'Miami International Autodrome',
    location: 'Miami, United States',
    date: '03 May 2026',
    status: 'OFFICIAL FIA CLASSIFICATION',
    lapsTotal: 57,
    winningTeam: 'Visa Cash App Racing Bulls F1 Team',
    winningTeamId: 'rb',
    winningStop: '2.08s',
    winningDriver: 'Arvid Lindblad',
    winningDriverNumber: 41,
    stops: [
      {
        rank: 1,
        stop: 1,
        driverId: 'lindblad',
        driverName: 'Arvid Lindblad',
        driverCode: 'LIN',
        driverNumber: 41,
        teamId: 'rb',
        teamName: 'Racing Bulls',
        teamColor: '#6692FF',
        lap: 29,
        stationaryDuration: '2.08s',
        stationaryTime: 2.08,
        pitLaneDuration: '22.1s',
        tyresFitted: 'Hard',
        isFastest: true,
      },
      {
        rank: 2,
        stop: 1,
        driverId: 'max_verstappen',
        driverName: 'Max Verstappen',
        driverCode: 'VER',
        driverNumber: 3,
        teamId: 'red_bull',
        teamName: 'Red Bull Racing',
        teamColor: '#3671C6',
        lap: 27,
        stationaryDuration: '2.12s',
        stationaryTime: 2.12,
        pitLaneDuration: '22.3s',
        tyresFitted: 'Hard',
      },
      {
        rank: 3,
        stop: 1,
        driverId: 'norris',
        driverName: 'Lando Norris',
        driverCode: 'NOR',
        driverNumber: 4,
        teamId: 'mclaren',
        teamName: 'McLaren',
        teamColor: '#FF8000',
        lap: 31,
        stationaryDuration: '2.15s',
        stationaryTime: 2.15,
        pitLaneDuration: '22.4s',
        tyresFitted: 'Hard',
      },
      {
        rank: 4,
        stop: 1,
        driverId: 'russell',
        driverName: 'George Russell',
        driverCode: 'RUS',
        driverNumber: 63,
        teamId: 'mercedes',
        teamName: 'Mercedes',
        teamColor: '#27F4D2',
        lap: 28,
        stationaryDuration: '2.20s',
        stationaryTime: 2.20,
        pitLaneDuration: '22.5s',
        tyresFitted: 'Hard',
      },
    ],
  },
  1: {
    round: 1,
    season: '2026',
    gpName: 'Australian Grand Prix',
    officialTitle: 'FORMULA 1 ROLEX AUSTRALIAN GRAND PRIX 2026',
    circuitName: 'Albert Park Circuit',
    location: 'Melbourne, Australia',
    date: '15 Mar 2026',
    status: 'OFFICIAL FIA CLASSIFICATION',
    lapsTotal: 58,
    winningTeam: 'Mercedes-AMG PETRONAS F1 Team',
    winningTeamId: 'mercedes',
    winningStop: '2.17s',
    winningDriver: 'Kimi Antonelli',
    winningDriverNumber: 12,
    stops: [
      {
        rank: 1,
        stop: 1,
        driverId: 'antonelli',
        driverName: 'Kimi Antonelli',
        driverCode: 'ANT',
        driverNumber: 12,
        teamId: 'mercedes',
        teamName: 'Mercedes',
        teamColor: '#27F4D2',
        lap: 19,
        stationaryDuration: '2.17s',
        stationaryTime: 2.17,
        pitLaneDuration: '22.4s',
        tyresFitted: 'Hard',
        isFastest: true,
      },
      {
        rank: 2,
        stop: 1,
        driverId: 'max_verstappen',
        driverName: 'Max Verstappen',
        driverCode: 'VER',
        driverNumber: 3,
        teamId: 'red_bull',
        teamName: 'Red Bull Racing',
        teamColor: '#3671C6',
        lap: 21,
        stationaryDuration: '2.20s',
        stationaryTime: 2.20,
        pitLaneDuration: '22.6s',
        tyresFitted: 'Hard',
      },
      {
        rank: 3,
        stop: 1,
        driverId: 'leclerc',
        driverName: 'Charles Leclerc',
        driverCode: 'LEC',
        driverNumber: 16,
        teamId: 'ferrari',
        teamName: 'Ferrari',
        teamColor: '#E8002D',
        lap: 22,
        stationaryDuration: '2.28s',
        stationaryTime: 2.28,
        pitLaneDuration: '22.7s',
        tyresFitted: 'Hard',
      },
      {
        rank: 4,
        stop: 1,
        driverId: 'piastri',
        driverName: 'Oscar Piastri',
        driverCode: 'PIA',
        driverNumber: 81,
        teamId: 'mclaren',
        teamName: 'McLaren',
        teamColor: '#FF8000',
        lap: 20,
        stationaryDuration: '2.32s',
        stationaryTime: 2.32,
        pitLaneDuration: '22.5s',
        tyresFitted: 'Hard',
      },
    ],
  },
};

// Default high-fidelity pit stop telemetry records for recent GP (Italian GP Monza)
export const RECENT_PIT_STOPS_DATA: PitStopEntry[] = OFFICIAL_GP_PIT_STOP_RECORDS[14].stops;

// Backwards-compatible aliases for search and askApex intelligence
export const TEAM_PIT_CREW_STANDINGS = DHL_PIT_STOP_STANDINGS;
export const TOP_SEASON_PIT_STOPS = RECENT_PIT_STOPS_DATA;
