export interface SeasonRaceFinish {
  raceName: string;
  finishPos: number;
  gridPos: number;
  delta: number;
  isWin: boolean;
  isPodium: boolean;
  isPoints: boolean;
  isDNF: boolean;
}

export interface SeasonDriverMetrics {
  driverId: string;
  currentRank: number;
  seasonPoints: number;
  seasonWins: number;
  seasonPodiums: number;
  seasonPoles: number;
  fastestLaps: number;
  dnfs: number;
  avgFinish: number;
  avgGrid: number;
  pointsPerRace: number;
  teamTenure: string;
  teammateH2H: {
    teammateName: string;
    qualiScore: string;
    raceScore: string;
    pointsSplit: [number, number];
    medianGapSeconds: string;
  };
  last5Races: SeasonRaceFinish[];
}

export const SEASON_2026_DRIVER_METRICS: Record<string, SeasonDriverMetrics> = {
  hamilton: {
    driverId: 'hamilton',
    currentRank: 3,
    seasonPoints: 191,
    seasonWins: 1,
    seasonPodiums: 5,
    seasonPoles: 0,
    fastestLaps: 2,
    dnfs: 1,
    avgFinish: 5.2,
    avgGrid: 4.4,
    pointsPerRace: 13.6,
    teamTenure: '2025 – Present',
    teammateH2H: {
      teammateName: 'Charles Leclerc',
      qualiScore: '6 — 8',
      raceScore: '8 — 6',
      pointsSplit: [53, 47],
      medianGapSeconds: '-0.045s',
    },
    last5Races: [
      { raceName: 'Spanish GP', finishPos: 22, gridPos: 4, delta: -18, isWin: false, isPodium: false, isPoints: false, isDNF: true },
      { raceName: 'Italian GP', finishPos: 6, gridPos: 4, delta: -2, isWin: false, isPodium: false, isPoints: true, isDNF: false },
      { raceName: 'Dutch GP', finishPos: 4, gridPos: 5, delta: 1, isWin: false, isPodium: false, isPoints: true, isDNF: false },
      { raceName: 'Hungarian GP', finishPos: 5, gridPos: 5, delta: 0, isWin: false, isPodium: false, isPoints: true, isDNF: false },
      { raceName: 'Belgian GP', finishPos: 4, gridPos: 5, delta: 1, isWin: false, isPodium: false, isPoints: true, isDNF: false },
    ],
  },
  max_verstappen: {
    driverId: 'max_verstappen',
    currentRank: 6,
    seasonPoints: 145,
    seasonWins: 0,
    seasonPodiums: 6,
    seasonPoles: 0,
    fastestLaps: 3,
    dnfs: 4,
    avgFinish: 8.4,
    avgGrid: 6.2,
    pointsPerRace: 10.4,
    teamTenure: '2016 – Present',
    teammateH2H: {
      teammateName: 'Isack Hadjar',
      qualiScore: '8 — 3',
      raceScore: '8 — 3',
      pointsSplit: [58, 42],
      medianGapSeconds: '-0.315s',
    },
    last5Races: [
      { raceName: 'Spanish GP', finishPos: 2, gridPos: 3, delta: 1, isWin: false, isPodium: true, isPoints: true, isDNF: false },
      { raceName: 'Italian GP', finishPos: 3, gridPos: 5, delta: 2, isWin: false, isPodium: true, isPoints: true, isDNF: false },
      { raceName: 'Dutch GP', finishPos: 22, gridPos: 7, delta: -15, isWin: false, isPodium: false, isPoints: false, isDNF: true },
      { raceName: 'Hungarian GP', finishPos: 2, gridPos: 4, delta: 2, isWin: false, isPodium: true, isPoints: true, isDNF: false },
      { raceName: 'Belgian GP', finishPos: 3, gridPos: 2, delta: -1, isWin: false, isPodium: true, isPoints: true, isDNF: false },
    ],
  },
  norris: {
    driverId: 'norris',
    currentRank: 4,
    seasonPoints: 186,
    seasonWins: 2,
    seasonPodiums: 5,
    seasonPoles: 4,
    fastestLaps: 3,
    dnfs: 3,
    avgFinish: 7.1,
    avgGrid: 5.1,
    pointsPerRace: 13.3,
    teamTenure: '2019 – Present',
    teammateH2H: {
      teammateName: 'Oscar Piastri',
      qualiScore: '8 — 6',
      raceScore: '8 — 6',
      pointsSplit: [61, 39],
      medianGapSeconds: '-0.145s',
    },
    last5Races: [
      { raceName: 'Spanish GP', finishPos: 3, gridPos: 1, delta: -2, isWin: false, isPodium: true, isPoints: true, isDNF: false },
      { raceName: 'Italian GP', finishPos: 4, gridPos: 8, delta: 4, isWin: false, isPodium: false, isPoints: true, isDNF: false },
      { raceName: 'Dutch GP', finishPos: 1, gridPos: 1, delta: 0, isWin: true, isPodium: true, isPoints: true, isDNF: false },
      { raceName: 'Hungarian GP', finishPos: 1, gridPos: 1, delta: 0, isWin: true, isPodium: true, isPoints: true, isDNF: false },
      { raceName: 'Belgian GP', finishPos: 7, gridPos: 13, delta: 6, isWin: false, isPodium: false, isPoints: true, isDNF: false },
    ],
  },
  piastri: {
    driverId: 'piastri',
    currentRank: 7,
    seasonPoints: 120,
    seasonWins: 0,
    seasonPodiums: 2,
    seasonPoles: 0,
    fastestLaps: 1,
    dnfs: 3,
    avgFinish: 7.2,
    avgGrid: 5.6,
    pointsPerRace: 8.6,
    teamTenure: '2023 – Present',
    teammateH2H: {
      teammateName: 'Lando Norris',
      qualiScore: '6 — 8',
      raceScore: '6 — 8',
      pointsSplit: [39, 61],
      medianGapSeconds: '+0.145s',
    },
    last5Races: [
      { raceName: 'Spanish GP', finishPos: 8, gridPos: 7, delta: -1, isWin: false, isPodium: false, isPoints: true, isDNF: false },
      { raceName: 'Italian GP', finishPos: 5, gridPos: 6, delta: 1, isWin: false, isPodium: false, isPoints: true, isDNF: false },
      { raceName: 'Dutch GP', finishPos: 6, gridPos: 4, delta: -2, isWin: false, isPodium: false, isPoints: true, isDNF: false },
      { raceName: 'Hungarian GP', finishPos: 20, gridPos: 3, delta: -17, isWin: false, isPodium: false, isPoints: false, isDNF: true },
      { raceName: 'Belgian GP', finishPos: 5, gridPos: 6, delta: 1, isWin: false, isPodium: false, isPoints: true, isDNF: false },
    ],
  },
  antonelli: {
    driverId: 'antonelli',
    currentRank: 1,
    seasonPoints: 292,
    seasonWins: 8,
    seasonPodiums: 12,
    seasonPoles: 6,
    fastestLaps: 3,
    dnfs: 1,
    avgFinish: 3.5,
    avgGrid: 3.4,
    pointsPerRace: 20.9,
    teamTenure: '2025 – Present',
    teammateH2H: {
      teammateName: 'George Russell',
      qualiScore: '7 — 7',
      raceScore: '10 — 4',
      pointsSplit: [58, 42],
      medianGapSeconds: '-0.085s',
    },
    last5Races: [
      { raceName: 'Spanish GP', finishPos: 1, gridPos: 2, delta: 1, isWin: true, isPodium: true, isPoints: true, isDNF: false },
      { raceName: 'Italian GP', finishPos: 1, gridPos: 19, delta: 18, isWin: true, isPodium: true, isPoints: true, isDNF: false },
      { raceName: 'Dutch GP', finishPos: 2, gridPos: 3, delta: 1, isWin: false, isPodium: true, isPoints: true, isDNF: false },
      { raceName: 'Hungarian GP', finishPos: 3, gridPos: 7, delta: 4, isWin: false, isPodium: true, isPoints: true, isDNF: false },
      { raceName: 'Belgian GP', finishPos: 1, gridPos: 1, delta: 0, isWin: true, isPodium: true, isPoints: true, isDNF: false },
    ],
  },
  russell: {
    driverId: 'russell',
    currentRank: 2,
    seasonPoints: 211,
    seasonWins: 2,
    seasonPodiums: 7,
    seasonPoles: 4,
    fastestLaps: 2,
    dnfs: 2,
    avgFinish: 6.1,
    avgGrid: 3.0,
    pointsPerRace: 15.1,
    teamTenure: '2022 – Present',
    teammateH2H: {
      teammateName: 'Andrea Kimi Antonelli',
      qualiScore: '7 — 7',
      raceScore: '4 — 10',
      pointsSplit: [42, 58],
      medianGapSeconds: '+0.085s',
    },
    last5Races: [
      { raceName: 'Spanish GP', finishPos: 5, gridPos: 6, delta: 1, isWin: false, isPodium: false, isPoints: true, isDNF: false },
      { raceName: 'Italian GP', finishPos: 2, gridPos: 2, delta: 0, isWin: false, isPodium: true, isPoints: true, isDNF: false },
      { raceName: 'Dutch GP', finishPos: 3, gridPos: 2, delta: -1, isWin: false, isPodium: true, isPoints: true, isDNF: false },
      { raceName: 'Hungarian GP', finishPos: 7, gridPos: 6, delta: -1, isWin: false, isPodium: false, isPoints: true, isDNF: false },
      { raceName: 'Belgian GP', finishPos: 22, gridPos: 3, delta: -19, isWin: false, isPodium: false, isPoints: false, isDNF: true },
    ],
  },
  leclerc: {
    driverId: 'leclerc',
    currentRank: 5,
    seasonPoints: 167,
    seasonWins: 1,
    seasonPodiums: 4,
    seasonPoles: 0,
    fastestLaps: 1,
    dnfs: 3,
    avgFinish: 7.1,
    avgGrid: 4.4,
    pointsPerRace: 11.9,
    teamTenure: '2019 – Present',
    teammateH2H: {
      teammateName: 'Lewis Hamilton',
      qualiScore: '8 — 6',
      raceScore: '6 — 8',
      pointsSplit: [47, 53],
      medianGapSeconds: '+0.045s',
    },
    last5Races: [
      { raceName: 'Spanish GP', finishPos: 4, gridPos: 5, delta: 1, isWin: false, isPodium: false, isPoints: true, isDNF: false },
      { raceName: 'Italian GP', finishPos: 22, gridPos: 3, delta: -19, isWin: false, isPodium: false, isPoints: false, isDNF: true },
      { raceName: 'Dutch GP', finishPos: 5, gridPos: 6, delta: 1, isWin: false, isPodium: false, isPoints: true, isDNF: false },
      { raceName: 'Hungarian GP', finishPos: 4, gridPos: 2, delta: -2, isWin: false, isPodium: false, isPoints: true, isDNF: false },
      { raceName: 'Belgian GP', finishPos: 2, gridPos: 4, delta: 2, isWin: false, isPodium: true, isPoints: true, isDNF: false },
    ],
  },
  hadjar: {
    driverId: 'hadjar',
    currentRank: 8,
    seasonPoints: 71,
    seasonWins: 0,
    seasonPodiums: 1,
    seasonPoles: 0,
    fastestLaps: 0,
    dnfs: 2,
    avgFinish: 9.0,
    avgGrid: 9.3,
    pointsPerRace: 6.5,
    teamTenure: '2026 – Present',
    teammateH2H: {
      teammateName: 'Max Verstappen',
      qualiScore: '3 — 8',
      raceScore: '3 — 8',
      pointsSplit: [42, 58],
      medianGapSeconds: '+0.315s',
    },
    last5Races: [
      { raceName: 'Hungarian GP', finishPos: 6, gridPos: 8, delta: 2, isWin: false, isPodium: false, isPoints: true, isDNF: false },
      { raceName: 'Belgian GP', finishPos: 6, gridPos: 21, delta: 15, isWin: false, isPodium: false, isPoints: true, isDNF: false },
      { raceName: 'British GP', finishPos: 5, gridPos: 5, delta: 0, isWin: false, isPodium: false, isPoints: true, isDNF: false },
      { raceName: 'Austrian GP', finishPos: 6, gridPos: 8, delta: 2, isWin: false, isPodium: false, isPoints: true, isDNF: false },
      { raceName: 'Spanish GP', finishPos: 6, gridPos: 6, delta: 0, isWin: false, isPodium: false, isPoints: true, isDNF: false },
    ],
  },
  lawson: {
    driverId: 'lawson',
    currentRank: 9,
    seasonPoints: 59,
    seasonWins: 0,
    seasonPodiums: 0,
    seasonPoles: 0,
    fastestLaps: 0,
    dnfs: 1,
    avgFinish: 9.4,
    avgGrid: 11.0,
    pointsPerRace: 4.2,
    teamTenure: '2025 – Present',
    teammateH2H: {
      teammateName: 'Arvid Lindblad',
      qualiScore: '8 — 6',
      raceScore: '10 — 4',
      pointsSplit: [65, 35],
      medianGapSeconds: '-0.120s',
    },
    last5Races: [
      { raceName: 'Spanish GP', finishPos: 6, gridPos: 8, delta: 2, isWin: false, isPodium: false, isPoints: true, isDNF: false },
      { raceName: 'Italian GP', finishPos: 14, gridPos: 22, delta: 8, isWin: false, isPodium: false, isPoints: false, isDNF: false },
      { raceName: 'Dutch GP', finishPos: 7, gridPos: 8, delta: 1, isWin: false, isPodium: false, isPoints: true, isDNF: false },
      { raceName: 'Hungarian GP', finishPos: 8, gridPos: 11, delta: 3, isWin: false, isPodium: false, isPoints: true, isDNF: false },
      { raceName: 'Belgian GP', finishPos: 12, gridPos: 9, delta: -3, isWin: false, isPodium: false, isPoints: false, isDNF: false },
    ],
  },
  gasly: {
    driverId: 'gasly',
    currentRank: 10,
    seasonPoints: 41,
    seasonWins: 0,
    seasonPodiums: 0,
    seasonPoles: 0,
    fastestLaps: 0,
    dnfs: 1,
    avgFinish: 10.1,
    avgGrid: 10.6,
    pointsPerRace: 2.9,
    teamTenure: '2023 – Present',
    teammateH2H: {
      teammateName: 'Franco Colapinto',
      qualiScore: '10 — 4',
      raceScore: '9 — 5',
      pointsSplit: [59, 41],
      medianGapSeconds: '-0.110s',
    },
    last5Races: [
      { raceName: 'Spanish GP', finishPos: 12, gridPos: 14, delta: 2, isWin: false, isPodium: false, isPoints: false, isDNF: false },
      { raceName: 'Italian GP', finishPos: 7, gridPos: 1, delta: -6, isWin: false, isPodium: false, isPoints: true, isDNF: false },
      { raceName: 'Dutch GP', finishPos: 10, gridPos: 11, delta: 1, isWin: false, isPodium: false, isPoints: true, isDNF: false },
      { raceName: 'Hungarian GP', finishPos: 12, gridPos: 12, delta: 0, isWin: false, isPodium: false, isPoints: false, isDNF: false },
      { raceName: 'Belgian GP', finishPos: 11, gridPos: 10, delta: -1, isWin: false, isPodium: false, isPoints: false, isDNF: false },
    ],
  },
  lindblad: {
    driverId: 'lindblad',
    currentRank: 11,
    seasonPoints: 31,
    seasonWins: 0,
    seasonPodiums: 0,
    seasonPoles: 0,
    fastestLaps: 0,
    dnfs: 1,
    avgFinish: 10.7,
    avgGrid: 10.6,
    pointsPerRace: 2.2,
    teamTenure: '2026 – Present',
    teammateH2H: {
      teammateName: 'Liam Lawson',
      qualiScore: '6 — 8',
      raceScore: '4 — 10',
      pointsSplit: [35, 65],
      medianGapSeconds: '+0.120s',
    },
    last5Races: [
      { raceName: 'Spanish GP', finishPos: 9, gridPos: 10, delta: 1, isWin: false, isPodium: false, isPoints: true, isDNF: false },
      { raceName: 'Italian GP', finishPos: 8, gridPos: 9, delta: 1, isWin: false, isPodium: false, isPoints: true, isDNF: false },
      { raceName: 'Dutch GP', finishPos: 12, gridPos: 10, delta: -2, isWin: false, isPodium: false, isPoints: false, isDNF: false },
      { raceName: 'Hungarian GP', finishPos: 10, gridPos: 9, delta: -1, isWin: false, isPodium: false, isPoints: true, isDNF: false },
      { raceName: 'Belgian GP', finishPos: 9, gridPos: 7, delta: -2, isWin: false, isPodium: false, isPoints: true, isDNF: false },
    ],
  },
  colapinto: {
    driverId: 'colapinto',
    currentRank: 12,
    seasonPoints: 27,
    seasonWins: 0,
    seasonPodiums: 0,
    seasonPoles: 0,
    fastestLaps: 0,
    dnfs: 0,
    avgFinish: 11.1,
    avgGrid: 12.6,
    pointsPerRace: 1.9,
    teamTenure: '2025 – Present',
    teammateH2H: {
      teammateName: 'Pierre Gasly',
      qualiScore: '4 — 10',
      raceScore: '5 — 9',
      pointsSplit: [41, 59],
      medianGapSeconds: '+0.110s',
    },
    last5Races: [
      { raceName: 'Spanish GP', finishPos: 7, gridPos: 9, delta: 2, isWin: false, isPodium: false, isPoints: true, isDNF: false },
      { raceName: 'Italian GP', finishPos: 9, gridPos: 7, delta: -2, isWin: false, isPodium: false, isPoints: true, isDNF: false },
      { raceName: 'Dutch GP', finishPos: 14, gridPos: 14, delta: 0, isWin: false, isPodium: false, isPoints: false, isDNF: false },
      { raceName: 'Hungarian GP', finishPos: 15, gridPos: 13, delta: -2, isWin: false, isPodium: false, isPoints: false, isDNF: false },
      { raceName: 'Belgian GP', finishPos: 10, gridPos: 11, delta: 1, isWin: false, isPodium: false, isPoints: true, isDNF: false },
    ],
  },
  bearman: {
    driverId: 'bearman',
    currentRank: 13,
    seasonPoints: 18,
    seasonWins: 0,
    seasonPodiums: 0,
    seasonPoles: 0,
    fastestLaps: 0,
    dnfs: 4,
    avgFinish: 14.5,
    avgGrid: 15.1,
    pointsPerRace: 1.3,
    teamTenure: '2025 – Present',
    teammateH2H: {
      teammateName: 'Esteban Ocon',
      qualiScore: '9 — 5',
      raceScore: '8 — 6',
      pointsSplit: [85, 15],
      medianGapSeconds: '-0.170s',
    },
    last5Races: [
      { raceName: 'Spanish GP', finishPos: 16, gridPos: 22, delta: 6, isWin: false, isPodium: false, isPoints: false, isDNF: false },
      { raceName: 'Italian GP', finishPos: 15, gridPos: 11, delta: -4, isWin: false, isPodium: false, isPoints: false, isDNF: false },
      { raceName: 'Dutch GP', finishPos: 21, gridPos: 20, delta: -1, isWin: false, isPodium: false, isPoints: false, isDNF: true },
      { raceName: 'Hungarian GP', finishPos: 19, gridPos: 17, delta: -2, isWin: false, isPodium: false, isPoints: false, isDNF: false },
      { raceName: 'Belgian GP', finishPos: 14, gridPos: 14, delta: 0, isWin: false, isPodium: false, isPoints: false, isDNF: false },
    ],
  },
  bortoleto: {
    driverId: 'bortoleto',
    currentRank: 14,
    seasonPoints: 10,
    seasonWins: 0,
    seasonPodiums: 0,
    seasonPoles: 0,
    fastestLaps: 0,
    dnfs: 1,
    avgFinish: 11.8,
    avgGrid: 12.4,
    pointsPerRace: 0.7,
    teamTenure: '2025 – Present',
    teammateH2H: {
      teammateName: 'Nico Hülkenberg',
      qualiScore: '7 — 7',
      raceScore: '8 — 6',
      pointsSplit: [59, 41],
      medianGapSeconds: '-0.035s',
    },
    last5Races: [
      { raceName: 'Spanish GP', finishPos: 13, gridPos: 12, delta: -1, isWin: false, isPodium: false, isPoints: false, isDNF: false },
      { raceName: 'Italian GP', finishPos: 11, gridPos: 10, delta: -1, isWin: false, isPodium: false, isPoints: false, isDNF: false },
      { raceName: 'Dutch GP', finishPos: 13, gridPos: 9, delta: -4, isWin: false, isPodium: false, isPoints: false, isDNF: false },
      { raceName: 'Hungarian GP', finishPos: 11, gridPos: 14, delta: 3, isWin: false, isPodium: false, isPoints: false, isDNF: false },
      { raceName: 'Belgian GP', finishPos: 8, gridPos: 8, delta: 0, isWin: false, isPodium: false, isPoints: true, isDNF: false },
    ],
  },
  hulkenberg: {
    driverId: 'hulkenberg',
    currentRank: 15,
    seasonPoints: 7,
    seasonWins: 0,
    seasonPodiums: 0,
    seasonPoles: 0,
    fastestLaps: 0,
    dnfs: 4,
    avgFinish: 13.9,
    avgGrid: 11.6,
    pointsPerRace: 0.5,
    teamTenure: '2025 – Present',
    teammateH2H: {
      teammateName: 'Gabriel Bortoleto',
      qualiScore: '7 — 7',
      raceScore: '6 — 8',
      pointsSplit: [41, 59],
      medianGapSeconds: '+0.035s',
    },
    last5Races: [
      { raceName: 'Spanish GP', finishPos: 10, gridPos: 11, delta: 1, isWin: false, isPodium: false, isPoints: true, isDNF: false },
      { raceName: 'Italian GP', finishPos: 12, gridPos: 12, delta: 0, isWin: false, isPodium: false, isPoints: false, isDNF: false },
      { raceName: 'Dutch GP', finishPos: 8, gridPos: 13, delta: 5, isWin: false, isPodium: false, isPoints: true, isDNF: false },
      { raceName: 'Hungarian GP', finishPos: 9, gridPos: 10, delta: 1, isWin: false, isPodium: false, isPoints: true, isDNF: false },
      { raceName: 'Belgian GP', finishPos: 13, gridPos: 12, delta: -1, isWin: false, isPodium: false, isPoints: false, isDNF: false },
    ],
  },
  sainz: {
    driverId: 'sainz',
    currentRank: 16,
    seasonPoints: 6,
    seasonWins: 0,
    seasonPodiums: 0,
    seasonPoles: 0,
    fastestLaps: 0,
    dnfs: 3,
    avgFinish: 14.6,
    avgGrid: 16.3,
    pointsPerRace: 0.4,
    teamTenure: '2025 – Present',
    teammateH2H: {
      teammateName: 'Alexander Albon',
      qualiScore: '9 — 5',
      raceScore: '8 — 6',
      pointsSplit: [55, 45],
      medianGapSeconds: '-0.080s',
    },
    last5Races: [
      { raceName: 'Spanish GP', finishPos: 19, gridPos: 20, delta: 1, isWin: false, isPodium: false, isPoints: false, isDNF: true },
      { raceName: 'Italian GP', finishPos: 13, gridPos: 13, delta: 0, isWin: false, isPodium: false, isPoints: false, isDNF: false },
      { raceName: 'Dutch GP', finishPos: 15, gridPos: 17, delta: 2, isWin: false, isPodium: false, isPoints: false, isDNF: false },
      { raceName: 'Hungarian GP', finishPos: 13, gridPos: 18, delta: 5, isWin: false, isPodium: false, isPoints: false, isDNF: false },
      { raceName: 'Belgian GP', finishPos: 16, gridPos: 18, delta: 2, isWin: false, isPodium: false, isPoints: false, isDNF: false },
    ],
  },
  albon: {
    driverId: 'albon',
    currentRank: 17,
    seasonPoints: 5,
    seasonWins: 0,
    seasonPodiums: 0,
    seasonPoles: 0,
    fastestLaps: 0,
    dnfs: 4,
    avgFinish: 16.4,
    avgGrid: 16.9,
    pointsPerRace: 0.4,
    teamTenure: '2022 – Present',
    teammateH2H: {
      teammateName: 'Carlos Sainz',
      qualiScore: '5 — 9',
      raceScore: '6 — 8',
      pointsSplit: [45, 55],
      medianGapSeconds: '+0.080s',
    },
    last5Races: [
      { raceName: 'Spanish GP', finishPos: 15, gridPos: 16, delta: 1, isWin: false, isPodium: false, isPoints: false, isDNF: false },
      { raceName: 'Italian GP', finishPos: 17, gridPos: 20, delta: 3, isWin: false, isPodium: false, isPoints: false, isDNF: false },
      { raceName: 'Dutch GP', finishPos: 17, gridPos: 16, delta: -1, isWin: false, isPodium: false, isPoints: false, isDNF: true },
      { raceName: 'Hungarian GP', finishPos: 17, gridPos: 19, delta: 2, isWin: false, isPodium: false, isPoints: false, isDNF: false },
      { raceName: 'Belgian GP', finishPos: 15, gridPos: 15, delta: 0, isWin: false, isPodium: false, isPoints: false, isDNF: false },
    ],
  },
  ocon: {
    driverId: 'ocon',
    currentRank: 18,
    seasonPoints: 3,
    seasonWins: 0,
    seasonPodiums: 0,
    seasonPoles: 0,
    fastestLaps: 0,
    dnfs: 1,
    avgFinish: 13.7,
    avgGrid: 14.9,
    pointsPerRace: 0.2,
    teamTenure: '2025 – Present',
    teammateH2H: {
      teammateName: 'Oliver Bearman',
      qualiScore: '5 — 9',
      raceScore: '6 — 8',
      pointsSplit: [15, 85],
      medianGapSeconds: '+0.170s',
    },
    last5Races: [
      { raceName: 'Spanish GP', finishPos: 11, gridPos: 13, delta: 2, isWin: false, isPodium: false, isPoints: false, isDNF: false },
      { raceName: 'Italian GP', finishPos: 16, gridPos: 14, delta: -2, isWin: false, isPodium: false, isPoints: false, isDNF: false },
      { raceName: 'Dutch GP', finishPos: 19, gridPos: 15, delta: -4, isWin: false, isPodium: false, isPoints: false, isDNF: true },
      { raceName: 'Hungarian GP', finishPos: 16, gridPos: 15, delta: -1, isWin: false, isPodium: false, isPoints: false, isDNF: false },
      { raceName: 'Belgian GP', finishPos: 17, gridPos: 16, delta: -1, isWin: false, isPodium: false, isPoints: false, isDNF: false },
    ],
  },
  alonso: {
    driverId: 'alonso',
    currentRank: 19,
    seasonPoints: 3,
    seasonWins: 0,
    seasonPodiums: 0,
    seasonPoles: 0,
    fastestLaps: 0,
    dnfs: 5,
    avgFinish: 16.6,
    avgGrid: 19.4,
    pointsPerRace: 0.2,
    teamTenure: '2023 – Present',
    teammateH2H: {
      teammateName: 'Lance Stroll',
      qualiScore: '11 — 3',
      raceScore: '10 — 4',
      pointsSplit: [100, 0],
      medianGapSeconds: '-0.420s',
    },
    last5Races: [
      { raceName: 'Spanish GP', finishPos: 17, gridPos: 17, delta: 0, isWin: false, isPodium: false, isPoints: false, isDNF: false },
      { raceName: 'Italian GP', finishPos: 21, gridPos: 21, delta: 0, isWin: false, isPodium: false, isPoints: false, isDNF: true },
      { raceName: 'Dutch GP', finishPos: 9, gridPos: 18, delta: 9, isWin: false, isPodium: false, isPoints: true, isDNF: false },
      { raceName: 'Hungarian GP', finishPos: 14, gridPos: 16, delta: 2, isWin: false, isPodium: false, isPoints: false, isDNF: false },
      { raceName: 'Belgian GP', finishPos: 19, gridPos: 22, delta: 3, isWin: false, isPodium: false, isPoints: false, isDNF: false },
    ],
  },
  tsunoda: {
    driverId: 'tsunoda',
    currentRank: 20,
    seasonPoints: 1,
    seasonWins: 0,
    seasonPodiums: 0,
    seasonPoles: 0,
    fastestLaps: 0,
    dnfs: 0,
    avgFinish: 11.7,
    avgGrid: 14.0,
    pointsPerRace: 0.3,
    teamTenure: '2021 – Present',
    teammateH2H: {
      teammateName: 'Liam Lawson',
      qualiScore: '2 — 1',
      raceScore: '2 — 1',
      pointsSplit: [100, 0],
      medianGapSeconds: '-0.050s',
    },
    last5Races: [
      { raceName: 'Spanish GP', finishPos: 14, gridPos: 15, delta: 1, isWin: false, isPodium: false, isPoints: false, isDNF: false },
      { raceName: 'Italian GP', finishPos: 10, gridPos: 15, delta: 5, isWin: false, isPodium: false, isPoints: true, isDNF: false },
      { raceName: 'Dutch GP', finishPos: 11, gridPos: 12, delta: 1, isWin: false, isPodium: false, isPoints: false, isDNF: false },
    ],
  },
  stroll: {
    driverId: 'stroll',
    currentRank: 21,
    seasonPoints: 0,
    seasonWins: 0,
    seasonPodiums: 0,
    seasonPoles: 0,
    fastestLaps: 0,
    dnfs: 6,
    avgFinish: 18.2,
    avgGrid: 19.8,
    pointsPerRace: 0.0,
    teamTenure: '2019 – Present',
    teammateH2H: {
      teammateName: 'Fernando Alonso',
      qualiScore: '3 — 11',
      raceScore: '4 — 10',
      pointsSplit: [0, 100],
      medianGapSeconds: '+0.420s',
    },
    last5Races: [
      { raceName: 'Spanish GP', finishPos: 21, gridPos: 21, delta: 0, isWin: false, isPodium: false, isPoints: false, isDNF: true },
      { raceName: 'Italian GP', finishPos: 18, gridPos: 17, delta: -1, isWin: false, isPodium: false, isPoints: false, isDNF: false },
      { raceName: 'Dutch GP', finishPos: 16, gridPos: 19, delta: 3, isWin: false, isPodium: false, isPoints: false, isDNF: false },
      { raceName: 'Hungarian GP', finishPos: 18, gridPos: 20, delta: 2, isWin: false, isPodium: false, isPoints: false, isDNF: false },
      { raceName: 'Belgian GP', finishPos: 20, gridPos: 20, delta: 0, isWin: false, isPodium: false, isPoints: false, isDNF: false },
    ],
  },
  bottas: {
    driverId: 'bottas',
    currentRank: 22,
    seasonPoints: 0,
    seasonWins: 0,
    seasonPodiums: 0,
    seasonPoles: 0,
    fastestLaps: 0,
    dnfs: 6,
    avgFinish: 18.6,
    avgGrid: 19.3,
    pointsPerRace: 0.0,
    teamTenure: '2026 – Present',
    teammateH2H: {
      teammateName: 'Sergio Pérez',
      qualiScore: '8 — 6',
      raceScore: '7 — 7',
      pointsSplit: [50, 50],
      medianGapSeconds: '-0.030s',
    },
    last5Races: [
      { raceName: 'Spanish GP', finishPos: 18, gridPos: 19, delta: 1, isWin: false, isPodium: false, isPoints: false, isDNF: false },
      { raceName: 'Italian GP', finishPos: 19, gridPos: 16, delta: -3, isWin: false, isPodium: false, isPoints: false, isDNF: false },
      { raceName: 'Dutch GP', finishPos: 18, gridPos: 21, delta: 3, isWin: false, isPodium: false, isPoints: false, isDNF: true },
      { raceName: 'Hungarian GP', finishPos: 22, gridPos: 21, delta: -1, isWin: false, isPodium: false, isPoints: false, isDNF: true },
      { raceName: 'Belgian GP', finishPos: 18, gridPos: 17, delta: -1, isWin: false, isPodium: false, isPoints: false, isDNF: false },
    ],
  },
  perez: {
    driverId: 'perez',
    currentRank: 23,
    seasonPoints: 0,
    seasonWins: 0,
    seasonPodiums: 0,
    seasonPoles: 0,
    fastestLaps: 0,
    dnfs: 6,
    avgFinish: 18.8,
    avgGrid: 19.5,
    pointsPerRace: 0.0,
    teamTenure: '2026 – Present',
    teammateH2H: {
      teammateName: 'Valtteri Bottas',
      qualiScore: '6 — 8',
      raceScore: '7 — 7',
      pointsSplit: [50, 50],
      medianGapSeconds: '+0.030s',
    },
    last5Races: [
      { raceName: 'Spanish GP', finishPos: 20, gridPos: 18, delta: -2, isWin: false, isPodium: false, isPoints: false, isDNF: true },
      { raceName: 'Italian GP', finishPos: 20, gridPos: 18, delta: -2, isWin: false, isPodium: false, isPoints: false, isDNF: false },
      { raceName: 'Dutch GP', finishPos: 20, gridPos: 22, delta: 2, isWin: false, isPodium: false, isPoints: false, isDNF: true },
      { raceName: 'Hungarian GP', finishPos: 21, gridPos: 22, delta: 1, isWin: false, isPodium: false, isPoints: false, isDNF: true },
      { raceName: 'Belgian GP', finishPos: 21, gridPos: 19, delta: -2, isWin: false, isPodium: false, isPoints: false, isDNF: true },
    ],
  },
};

export function getSeason2026Metrics(driverId: string): SeasonDriverMetrics | null {
  const norm = driverId.toLowerCase().replace(/[\s-]+/g, '_');
  if (SEASON_2026_DRIVER_METRICS[norm]) return SEASON_2026_DRIVER_METRICS[norm];

  for (const [k, v] of Object.entries(SEASON_2026_DRIVER_METRICS)) {
    if (norm.includes(k) || k.includes(norm)) return v;
  }
  return null;
}
