import { TeamMeta } from './types';

export const F1_TEAMS: Record<string, TeamMeta> = {
  ferrari: {
    id: 'ferrari',
    name: 'Ferrari',
    fullName: 'Scuderia Ferrari HP',
    color: '#E8002D',
    secondaryColor: '#FFF200',
    textColor: '#FFFFFF',
    accentGlow: 'rgba(232, 0, 45, 0.4)',
    powerUnit: 'Ferrari',
    base: 'Maranello, Italy',
    teamPrincipal: 'Frédéric Vasseur',
    championships: 16,
    drivers: ['leclerc', 'hamilton', 'sainz'],
    academyDrivers: ['Dino Beganovic (F2)', 'Tuukka Taponen (F3)', 'Maya Weug (F1 Academy)', 'Aurelia Nobels (F1 Academy)'],
    fastestSeasonPitStop: { time: '2.14s', round: 'Round 12 (Spa)', driver: 'Charles Leclerc' },
  },
  mclaren: {
    id: 'mclaren',
    name: 'McLaren',
    fullName: 'McLaren Formula 1 Team',
    color: '#FF8000',
    secondaryColor: '#47C7FC',
    textColor: '#FFFFFF',
    accentGlow: 'rgba(255, 128, 0, 0.4)',
    powerUnit: 'Mercedes',
    base: 'Woking, United Kingdom',
    teamPrincipal: 'Andrea Stella',
    championships: 8,
    drivers: ['norris', 'piastri'],
    academyDrivers: ['Gabriel Bortoleto (F2)', 'Bianca Bustamante (F1 Academy)', 'Martinius Stenshorne (F3)', 'Alex Dunne (F3)'],
    fastestSeasonPitStop: { time: '1.95s', round: 'Round 14 (Zandvoort)', driver: 'Lando Norris' },
  },
  mercedes: {
    id: 'mercedes',
    name: 'Mercedes',
    fullName: 'Mercedes-AMG PETRONAS F1 Team',
    color: '#27F4D2',
    secondaryColor: '#C0C0C0',
    textColor: '#0A0A0F',
    accentGlow: 'rgba(39, 244, 210, 0.4)',
    powerUnit: 'Mercedes',
    base: 'Brackley, United Kingdom',
    teamPrincipal: 'Toto Wolff',
    championships: 8,
    drivers: ['russell', 'antonelli'],
    academyDrivers: ['Andrea Kimi Antonelli (F2)', 'Doriane Pin (F1 Academy)', 'Paul Aron (F2)', 'Alex Powell (F4)'],
    fastestSeasonPitStop: { time: '2.09s', round: 'Round 9 (Silverstone)', driver: 'George Russell' },
  },
  red_bull: {
    id: 'red_bull',
    name: 'Red Bull Racing',
    fullName: 'Oracle Red Bull Racing',
    color: '#3671C6',
    secondaryColor: '#FCD800',
    textColor: '#FFFFFF',
    accentGlow: 'rgba(54, 113, 198, 0.4)',
    powerUnit: 'Honda RBPT',
    base: 'Milton Keynes, United Kingdom',
    teamPrincipal: 'Christian Horner',
    championships: 6,
    drivers: ['max_verstappen', 'lawson', 'perez'],
    academyDrivers: ['Isack Hadjar (F2)', 'Arvid Lindblad (F2)', 'Pepe Martí (F2)', 'Oliver Goethe (F2)', 'Tim Tramnitz (F3)'],
    fastestSeasonPitStop: { time: '1.90s', round: 'Round 5 (Shanghai)', driver: 'Max Verstappen' },
  },
  aston_martin: {
    id: 'aston_martin',
    name: 'Aston Martin',
    fullName: 'Aston Martin Aramco F1 Team',
    color: '#229971',
    secondaryColor: '#CEDC00',
    textColor: '#FFFFFF',
    accentGlow: 'rgba(34, 153, 113, 0.4)',
    powerUnit: 'Mercedes',
    base: 'Silverstone, United Kingdom',
    teamPrincipal: 'Mike Krack',
    championships: 0,
    drivers: ['alonso', 'stroll'],
    academyDrivers: ['Jak Crawford (F2)', 'Tina Hausmann (F1 Academy)', 'Mari Boya (F3)'],
    fastestSeasonPitStop: { time: '2.21s', round: 'Round 8 (Barcelona)', driver: 'Fernando Alonso' },
  },
  alpine: {
    id: 'alpine',
    name: 'Alpine',
    fullName: 'BWT Alpine F1 Team',
    color: '#0090FF',
    secondaryColor: '#FF87BC',
    textColor: '#FFFFFF',
    accentGlow: 'rgba(0, 144, 255, 0.4)',
    powerUnit: 'Renault',
    base: 'Enstone, United Kingdom',
    teamPrincipal: 'Oliver Oakes',
    championships: 2,
    drivers: ['gasly', 'doohan'],
    academyDrivers: ['Abbi Pulling (F1 Academy)', 'Kush Maini (F2)', 'Gabriele Minì (F2)', 'Victor Martins (F2)'],
    fastestSeasonPitStop: { time: '2.27s', round: 'Round 10 (Hungaroring)', driver: 'Pierre Gasly' },
  },
  williams: {
    id: 'williams',
    name: 'Williams',
    fullName: 'Williams Racing',
    color: '#64C4FF',
    secondaryColor: '#002F6C',
    textColor: '#FFFFFF',
    accentGlow: 'rgba(100, 196, 255, 0.4)',
    powerUnit: 'Mercedes',
    base: 'Grove, United Kingdom',
    teamPrincipal: 'James Vowles',
    championships: 9,
    drivers: ['albon', 'sainz', 'colapinto'],
    academyDrivers: ['Franco Colapinto (F2)', 'Luke Browning (F2)', 'Lia Block (F1 Academy)', 'Zak O\'Sullivan (F2)'],
    fastestSeasonPitStop: { time: '2.19s', round: 'Round 4 (Suzuka)', driver: 'Alex Albon' },
  },
  rb: {
    id: 'rb',
    name: 'Racing Bulls',
    fullName: 'Visa Cash App RB F1 Team',
    color: '#6692FF',
    secondaryColor: '#E8002D',
    textColor: '#FFFFFF',
    accentGlow: 'rgba(102, 146, 255, 0.4)',
    powerUnit: 'Honda RBPT',
    base: 'Faenza, Italy',
    teamPrincipal: 'Laurent Mekies',
    championships: 0,
    drivers: ['tsunoda', 'hadjar', 'lawson'],
    academyDrivers: ['Ayumu Iwasa (Super Formula)', 'Enzo Deligny (FRECA)'],
    fastestSeasonPitStop: { time: '2.24s', round: 'Round 7 (Monaco)', driver: 'Yuki Tsunoda' },
  },
  haas: {
    id: 'haas',
    name: 'Haas',
    fullName: 'MoneyGram Haas F1 Team',
    color: '#E6002B',
    secondaryColor: '#B6BABD',
    textColor: '#FFFFFF',
    accentGlow: 'rgba(230, 0, 43, 0.4)',
    powerUnit: 'Ferrari',
    base: 'Kannapolis, United States',
    teamPrincipal: 'Ayao Komatsu',
    championships: 0,
    drivers: ['bearman', 'ocon'],
    academyDrivers: ['Chloe Chambers (F1 Academy)'],
    fastestSeasonPitStop: { time: '2.38s', round: 'Round 11 (Red Bull Ring)', driver: 'Nico Hulkenberg' },
  },
  sauber: {
    id: 'sauber',
    name: 'Kick Sauber',
    fullName: 'Stake F1 Team Kick Sauber',
    color: '#52E252',
    secondaryColor: '#000000',
    textColor: '#0A0A0F',
    accentGlow: 'rgba(82, 226, 82, 0.4)',
    powerUnit: 'Ferrari',
    base: 'Hinwil, Switzerland',
    teamPrincipal: 'Mattia Binotto',
    championships: 0,
    drivers: ['hulkenberg', 'bortoleto'],
    academyDrivers: ['Zane Maloney (F2)', 'Carrie Schreiner (F1 Academy)'],
    fastestSeasonPitStop: { time: '2.44s', round: 'Round 13 (Monza)', driver: 'Valtteri Bottas' },
  },
};

export function getTeamMeta(constructorIdOrName: string): TeamMeta {
  if (!constructorIdOrName) return F1_TEAMS.ferrari;
  const key = constructorIdOrName.toLowerCase().replace(/[\s-]+/g, '_');
  
  if (F1_TEAMS[key]) return F1_TEAMS[key];
  for (const [id, team] of Object.entries(F1_TEAMS)) {
    if (
      key.includes(id) ||
      team.name.toLowerCase().includes(key) ||
      key.includes(team.name.toLowerCase())
    ) {
      return team;
    }
  }

  // Fallback default neutral cyan/racing accent
  return {
    id: key,
    name: constructorIdOrName,
    fullName: constructorIdOrName,
    color: '#E10600',
    secondaryColor: '#FFFFFF',
    textColor: '#FFFFFF',
    accentGlow: 'rgba(225, 6, 0, 0.4)',
    powerUnit: 'Formula 1',
    base: 'Unknown',
    teamPrincipal: 'Team Principal',
    championships: 0,
    drivers: [],
  };
}

export const DRIVER_DETAILS: Record<
  string,
  {
    number: number;
    code: string;
    teamId: string;
    countryCode: string;
    countryFlag: string;
    birthDate: string;
    bio: string;
    worldTitles: number;
  }
> = {
  max_verstappen: {
    number: 1,
    code: 'VER',
    teamId: 'red_bull',
    countryCode: 'NLD',
    countryFlag: '🇳🇱',
    birthDate: '1997-09-30',
    bio: 'Multi-time World Champion known for relentless racecraft and unparalleled precision.',
    worldTitles: 4,
  },
  norris: {
    number: 4,
    code: 'NOR',
    teamId: 'mclaren',
    countryCode: 'GBR',
    countryFlag: '🇬🇧',
    birthDate: '1999-11-13',
    bio: 'McLaren talisman with explosive qualifying pace and championship-grade racecraft.',
    worldTitles: 0,
  },
  leclerc: {
    number: 16,
    code: 'LEC',
    teamId: 'ferrari',
    countryCode: 'MCO',
    countryFlag: '🇲🇨',
    birthDate: '1997-10-16',
    bio: 'Monegasque sensation, master of one-lap qualifying magic and Ferrari heartthrob.',
    worldTitles: 0,
  },
  hamilton: {
    number: 44,
    code: 'HAM',
    teamId: 'ferrari',
    countryCode: 'GBR',
    countryFlag: '🇬🇧',
    birthDate: '1985-01-07',
    bio: '7-time World Champion, statistically the greatest driver in F1 history in his iconic Ferrari era.',
    worldTitles: 7,
  },
  piastri: {
    number: 81,
    code: 'PIA',
    teamId: 'mclaren',
    countryCode: 'AUS',
    countryFlag: '🇦🇺',
    birthDate: '2001-04-06',
    bio: 'Ice-cool Australian prodigy with ruthless composure and Grand Prix winning racecraft.',
    worldTitles: 0,
  },
  russell: {
    number: 63,
    code: 'RUS',
    teamId: 'mercedes',
    countryCode: 'GBR',
    countryFlag: '🇬🇧',
    birthDate: '1998-02-15',
    bio: 'Mercedes team leader with clinical precision, relentless determination, and pole mastery.',
    worldTitles: 0,
  },
  sainz: {
    number: 55,
    code: 'SAI',
    teamId: 'williams',
    countryCode: 'ESP',
    countryFlag: '🇪🇸',
    birthDate: '1994-09-01',
    bio: 'The Smooth Operator — tactical genius with race-winning strategy intuition.',
    worldTitles: 0,
  },
  alonso: {
    number: 14,
    code: 'ALO',
    teamId: 'aston_martin',
    countryCode: 'ESP',
    countryFlag: '🇪🇸',
    birthDate: '1981-07-29',
    bio: 'Two-time World Champion, ageless gladiator who outfoxes competitors on every lap.',
    worldTitles: 2,
  },
  albon: {
    number: 23,
    code: 'ALB',
    teamId: 'williams',
    countryCode: 'THA',
    countryFlag: '🇹🇭',
    birthDate: '1996-03-23',
    bio: 'Williams anchor, renowned for tire conservation and extraordinary defensive drives.',
    worldTitles: 0,
  },
  gasly: {
    number: 10,
    code: 'GAS',
    teamId: 'alpine',
    countryCode: 'FRA',
    countryFlag: '🇫🇷',
    birthDate: '1996-02-07',
    bio: 'Grand Prix winner with fiery racecraft and relentless tenacity for Alpine.',
    worldTitles: 0,
  },
  tsunoda: {
    number: 22,
    code: 'TSU',
    teamId: 'rb',
    countryCode: 'JPN',
    countryFlag: '🇯🇵',
    birthDate: '2000-05-11',
    bio: 'Fast, passionate fan favorite with blisteringly quick reflexes on the track.',
    worldTitles: 0,
  },
  hulkenberg: {
    number: 27,
    code: 'HUL',
    teamId: 'sauber',
    countryCode: 'DEU',
    countryFlag: '🇩🇪',
    birthDate: '1987-08-19',
    bio: 'Veteran qualifying specialist known for extracting every tenth from any chassis.',
    worldTitles: 0,
  },
  bearman: {
    number: 87,
    code: 'BEA',
    teamId: 'haas',
    countryCode: 'GBR',
    countryFlag: '🇬🇧',
    birthDate: '2005-05-08',
    bio: 'Young British dynamo who took the paddock by storm with an unforgettable rookie debut.',
    worldTitles: 0,
  },
  ocon: {
    number: 31,
    code: 'OCO',
    teamId: 'haas',
    countryCode: 'FRA',
    countryFlag: '🇫🇷',
    birthDate: '1996-09-17',
    bio: 'Grand Prix winner known as one of the fiercest wheel-to-wheel racers on the grid.',
    worldTitles: 0,
  },
  stroll: {
    number: 18,
    code: 'STR',
    teamId: 'aston_martin',
    countryCode: 'CAN',
    countryFlag: '🇨🇦',
    birthDate: '1998-10-29',
    bio: 'Podium finisher and wet-weather virtuoso for Aston Martin.',
    worldTitles: 0,
  },
};

export const CIRCUIT_EXTRAS: Record<
  string,
  {
    corners: number;
    drsZones: number;
    lengthKm: number;
    lapRecord: string;
    recordHolder: string;
    recordYear: string;
  }
> = {
  albert_park: {
    corners: 14,
    drsZones: 4,
    lengthKm: 5.278,
    lapRecord: '1:19.813',
    recordHolder: 'Charles Leclerc',
    recordYear: '2024',
  },
  bahrain: {
    corners: 15,
    drsZones: 3,
    lengthKm: 5.412,
    lapRecord: '1:31.447',
    recordHolder: 'Pedro de la Rosa',
    recordYear: '2005',
  },
  shanghai: {
    corners: 16,
    drsZones: 2,
    lengthKm: 5.451,
    lapRecord: '1:32.238',
    recordHolder: 'Michael Schumacher',
    recordYear: '2004',
  },
  suzuka: {
    corners: 18,
    drsZones: 1,
    lengthKm: 5.807,
    lapRecord: '1:30.983',
    recordHolder: 'Lewis Hamilton',
    recordYear: '2019',
  },
  miami: {
    corners: 19,
    drsZones: 3,
    lengthKm: 5.412,
    lapRecord: '1:29.708',
    recordHolder: 'Max Verstappen',
    recordYear: '2023',
  },
  monaco: {
    corners: 19,
    drsZones: 1,
    lengthKm: 3.337,
    lapRecord: '1:12.909',
    recordHolder: 'Lewis Hamilton',
    recordYear: '2021',
  },
  catalunya: {
    corners: 14,
    drsZones: 2,
    lengthKm: 4.657,
    lapRecord: '1:16.330',
    recordHolder: 'Max Verstappen',
    recordYear: '2023',
  },
  red_bull_ring: {
    corners: 10,
    drsZones: 3,
    lengthKm: 4.318,
    lapRecord: '1:05.619',
    recordHolder: 'Carlos Sainz',
    recordYear: '2020',
  },
  silverstone: {
    corners: 18,
    drsZones: 2,
    lengthKm: 5.891,
    lapRecord: '1:27.097',
    recordHolder: 'Max Verstappen',
    recordYear: '2020',
  },
  spa: {
    corners: 19,
    drsZones: 2,
    lengthKm: 7.004,
    lapRecord: '1:44.701',
    recordHolder: 'Sergio Perez',
    recordYear: '2024',
  },
  monza: {
    corners: 11,
    drsZones: 2,
    lengthKm: 5.793,
    lapRecord: '1:21.046',
    recordHolder: 'Rubens Barrichello',
    recordYear: '2004',
  },
  marina_bay: {
    corners: 19,
    drsZones: 4,
    lengthKm: 4.940,
    lapRecord: '1:34.486',
    recordHolder: 'Daniel Ricciardo',
    recordYear: '2024',
  },
  americas: {
    corners: 20,
    drsZones: 2,
    lengthKm: 5.513,
    lapRecord: '1:36.169',
    recordHolder: 'Charles Leclerc',
    recordYear: '2019',
  },
  interlagos: {
    corners: 15,
    drsZones: 2,
    lengthKm: 4.309,
    lapRecord: '1:10.540',
    recordHolder: 'Valtteri Bottas',
    recordYear: '2018',
  },
  yas_marina: {
    corners: 16,
    drsZones: 2,
    lengthKm: 5.281,
    lapRecord: '1:26.103',
    recordHolder: 'Max Verstappen',
    recordYear: '2021',
  },
};
